use std::path::Path;

// W26: the protocol capability manifest's schema/parser/validator, shared
// with the crate (`protocols::manifest_def`).
#[allow(dead_code)]
#[path = "src/protocols/manifest_def.rs"]
mod manifest_def;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // rust-embed requires the bundle folders to exist at compile time, but
    // spa/dist is gitignored (build artifact). Drop in placeholders on fresh
    // clones; `make spa` replaces them with the real bundles (R23: the user
    // portal in spa/dist/app, the admin console in spa/dist/admin).
    for (dir, file) in [
        ("spa/dist/app", "index.html"),
        ("spa/dist/admin", "admin.html"),
    ] {
        let dir = Path::new(dir);
        std::fs::create_dir_all(dir)?;
        let index = dir.join(file);
        if !index.exists() {
            std::fs::write(
                &index,
                "<!doctype html><html><body>akari panel: frontend not built yet — run `make spa`.</body></html>",
            )?;
        }
    }
    println!("cargo:rerun-if-changed=spa/dist");
    emit_git_sha();
    println!("cargo:rerun-if-changed=proto/agent.proto");

    protocols_manifest()?;

    // Canonical contract lives in this repo (proto/agent.proto); akari-agent
    // vendors a copy (`make sync-proto` there).
    let fds = protox::compile(["proto/agent.proto"], ["proto"])?;
    tonic_prost_build::configure()
        .build_server(true)
        .build_client(true)
        .compile_fds(fds)?;
    Ok(())
}

/// `AKARI_GIT_SHA` (compile-time env, read by `akari --version` and the
/// `akari_build_info` metric): the CI/Docker build passes it explicitly
/// (`.git` is not in the Docker context); otherwise ask git; else "unknown".
fn emit_git_sha() {
    println!("cargo:rerun-if-env-changed=AKARI_GIT_SHA");
    // Re-run when the checked-out commit changes (worktrees keep their git
    // dir elsewhere, hence `--git-path`). Missing files are not listed:
    // cargo would treat them as always-changed.
    for name in ["HEAD", "logs/HEAD"] {
        if let Some(path) = git(&["rev-parse", "--git-path", name])
            && std::path::Path::new(&path).exists()
        {
            println!("cargo:rerun-if-changed={path}");
        }
    }
    let sha = std::env::var("AKARI_GIT_SHA")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .or_else(|| git(&["rev-parse", "--short=12", "HEAD"]))
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".into());
    println!("cargo:rustc-env=AKARI_GIT_SHA={sha}");
}

fn git(args: &[&str]) -> Option<String> {
    let out = std::process::Command::new("git")
        .args(args)
        .output()
        .ok()
        .filter(|o| o.status.success())?;
    Some(String::from_utf8(out.stdout).ok()?.trim().to_string())
}

/// W26: parse + validate `proto/protocols.toml` (a broken manifest fails
/// the build) and write it as Rust: `build()` reconstructs the manifest
/// (no runtime parse that could fail), plus `const` tables for the code
/// that needs them in const context (`crate::protocols::manifest`).
fn protocols_manifest() -> Result<(), Box<dyn std::error::Error>> {
    use manifest_def::Emit;
    println!("cargo:rerun-if-changed=proto/protocols.toml");
    println!("cargo:rerun-if-changed=src/protocols/manifest_def.rs");
    let src = std::fs::read_to_string("proto/protocols.toml")?;
    let m = manifest_def::parse(&src).map_err(|e| format!("proto/protocols.toml: {e}"))?;
    let mut out = String::from(
        "// @generated by build.rs from proto/protocols.toml (W26). Do not edit.\n\n\
         /// The manifest, rebuilt from the values validated at build time.\n\
         pub(super) fn build() -> Manifest {\n    ",
    );
    m.emit(&mut out);
    out.push_str("\n}\n\n");
    let konst = |owner: &str, id: &str, name: &str| {
        format!("{owner}_{id}_{name}")
            .to_ascii_uppercase()
            .replace('-', "_")
    };
    let strs = |v: &[String]| {
        v.iter()
            .map(|s| format!("{s:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    };
    out.push_str(&format!(
        "/// Wire names of the managed protocols, in manifest order.\n\
         pub const WIRE: [&str; {}] = [{}];\n",
        m.protocol.len(),
        strs(
            &m.protocol
                .iter()
                .map(|p| p.wire.clone())
                .collect::<Vec<_>>()
        )
    ));
    let mut fields: Vec<(&str, &str, &manifest_def::Field)> = Vec::new();
    for s in &m.security {
        fields.extend(s.field.iter().map(|f| ("security", s.id.as_str(), f)));
    }
    for t in &m.transport {
        fields.extend(t.field.iter().map(|f| ("transport", t.id.as_str(), f)));
    }
    for p in &m.protocol {
        fields.extend(p.option.iter().map(|f| ("protocol", p.id.as_str(), f)));
    }
    for (owner, id, f) in fields {
        if f.kind != "enum" {
            continue;
        }
        let name = konst(owner, id, &f.name);
        out.push_str(&format!(
            "/// Values of the {owner} {id:?} enum field {:?}.\n\
             pub const {name}: [&str; {}] = [{}];\n",
            f.name,
            f.values.len(),
            strs(&f.values)
        ));
        if !f.key_len.is_empty() {
            let pairs = f
                .values
                .iter()
                .zip(&f.key_len)
                .map(|(v, n)| format!("({v:?}, {n})"))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!(
                "/// (value, key length in bytes) of {name}.\n\
                 pub const {name}_KEY_LEN: [(&str, usize); {}] = [{pairs}];\n",
                f.values.len()
            ));
        }
    }
    let dest = Path::new(&std::env::var("OUT_DIR")?).join("protocols_manifest.rs");
    std::fs::write(dest, out)?;
    Ok(())
}
