-- Snapshot read (PERF.md "Snapshot read"): the primary key of
-- entrance_users carries the credential (INCLUDE protocol, account), so a
-- server's user set is an index-only scan per entrance instead of one heap
-- page per user. Production tables are written user by user (a user's rows
-- on all its entrances land together), which spreads one entrance's rows
-- over as many heap pages as it has users: 10k users = ~9.5k pages visited
-- per snapshot before this, ~190 index pages after.
--
-- The key columns and their order are unchanged (every lookup by
-- (entrance_id, user_id) and every ON CONFLICT keeps working); INCLUDE
-- columns are not in the inner pages, so the tree is no deeper. The index
-- replaces the old primary key (one index, not two): about 95 bytes more
-- per assignment.

-- An index tuple must fit a third of a page: credentials are a few dozen
-- bytes (generated by the panel only), the bound turns a hypothetical
-- oversized one into a clear constraint error instead of a b-tree one.
ALTER TABLE entrance_users ADD CONSTRAINT entrance_users_account_size
    CHECK (pg_column_size(account) <= 1024);

CREATE UNIQUE INDEX entrance_users_pkey_covering ON entrance_users
    USING btree (entrance_id, user_id) INCLUDE (protocol, account);
ALTER TABLE entrance_users DROP CONSTRAINT entrance_users_pkey;
ALTER TABLE entrance_users ADD CONSTRAINT entrance_users_pkey
    PRIMARY KEY USING INDEX entrance_users_pkey_covering;

-- An index-only scan reads the heap for every page not marked all-visible:
-- vacuum this table after ~1% of new or changed rows (default 20%), so
-- assignments added since the last vacuum stay a small share. Vacuuming it
-- is cheap: rows change rarely (assignment, credential reset), and pages
-- already all-visible are skipped.
ALTER TABLE entrance_users SET (
    autovacuum_vacuum_scale_factor = 0.01,
    autovacuum_vacuum_insert_scale_factor = 0.01
);
