// Server error texts of the admin console (W21, M6). Chinese only (R18),
// and admin-bundle only (R23: vite's userBundleGuard rejects this module in
// the portal build). Codes the portal can meet too are mapped in
// lib/errors.ts (CODE_KEYS, zh + en) and used here as the fallback.
// `{name}` placeholders are the error's params (plus `<p>_yuan` for each
// `<p>_cents`). scripts/check-error-codes.mjs fails when a server code
// (src/error_codes.txt) is mapped nowhere.
import { ApiError } from "./api";
import { CODE_KEYS, errorText, errorVars, zh } from "./errors";

export const ADMIN_CODES: Record<string, string> = {
  "order_admin.refund_gateway_failed": "支付宝拒绝了退款：{detail}（没有退出任何金额，可以重试或改用其他方式）",
  "order_admin.refund_in_progress": "该订单有一笔正在进行的原路退款，等支付宝确认后再操作",
  "order_admin.refund_original_conflict": "原路退款不能同时选择退到余额或填写后台已退金额",
  "order_admin.refund_original_range": "原路退款金额须为 0.01–{amount_yuan} 元",
  "order_admin.refund_original_unavailable": "该订单的支付方式未开启原路退款",
  "payments.refund_original_invalid": "「允许原路退款」只能是开或关",
  // Agent 更新检查
  "agent_update.asset_missing": "发布 {version} 缺少文件 {name}（发布未签名或不完整）",
  "agent_update.check_running": "已有更新检查在进行中，请稍候",
  "agent_update.checksum_mismatch": "{name} 与 SHA256SUMS 不符，已拒绝",
  "agent_update.checksum_missing": "SHA256SUMS 中没有 {name}",
  "agent_update.checksums_invalid": "SHA256SUMS 格式无效：{detail}",
  "agent_update.downgrade": "发布源的最新版本 {latest} 低于面板已有的 {have}，拒绝降级",
  "agent_update.fetch_failed": "下载 {what} 失败：{detail}",
  "agent_update.host_not_allowed": "{what} 位于发布源之外的主机 {host}，已拒绝",
  "agent_update.http_status": "下载 {what} 失败：HTTP {status}",
  "agent_update.platform_mismatch": "{name} 的平台是 {os}/{arch}，与文件名不符",
  "agent_update.prerelease": "发布源的最新发布 {version} 是草稿或预发布版本，未保存",
  "agent_update.release_invalid": "发布源返回的发布信息无效：{detail}",
  "agent_update.rollback_refused": "{name} 是回滚清单，不会自动保存；如确需回滚请手动上传",
  "agent_update.size_mismatch": "{name} 大小为 {got} 字节，与清单声明的 {want} 字节不符",
  "agent_update.source_invalid": "发布源地址无效：{detail}（须为 HTTPS）",
  "agent_update.timed_out": "更新检查超时，请稍后重试",
  "agent_update.too_large": "{what} 超过 {max} 字节上限",
  "agent_update.version_mismatch": "{name} 的版本是 {got}，与发布 {version} 不符",
  // 公告 / 知识库 / 品牌 / 邮件模板（Ops）
  "announcement.audience_invalid": "受众只能是全部用户、有生效套餐的用户或没有套餐的用户",
  "announcement.body_long": "正文不能超过 {max} 个字符",
  "announcement.body_required": "请填写正文",
  "announcement.mail_in_progress": "这条公告正在发送邮件，完成后才能再次发送",
  "announcement.mail_unavailable": "邮件发送尚未配置，请先在「系统设置 → 邮件」配置并启用 SMTP",
  "announcement.title_long": "标题不能超过 {max} 个字符",
  "announcement.title_multiline": "标题只能是一行",
  "announcement.title_required": "请填写标题",
  "announcement.window_invalid": "开始显示时间必须早于结束显示时间",
  // 审计规则（W29）
  "block_rule.builtin_fixed": "内置规则集只能开关和排序，不能修改或删除",
  "block_rule.days_range": "统计天数必须在 1–{max} 之间",
  "block_rule.entries_required": "规则至少需要一条内容",
  "block_rule.entry_invalid": "第 {line} 行不是有效的条目（类型：{kind}）",
  "block_rule.kind_invalid": "规则类型必须是域名、IP 或协议",
  "block_rule.name_long": "规则名称最多 {max} 个字符",
  "block_rule.name_multiline": "规则名称只能有一行",
  "block_rule.name_required": "请填写规则名称",
  "block_rule.pattern_long": "规则内容超过 {max} 字节",
  "block_rule.sort_range": "排序值必须在 ±{max} 之内",
  "block_rule.too_many_entries": "一条规则最多 {max} 条内容",
  "block_rule.too_many_rules": "自定义规则最多 {max} 条",
  "branding.footer_invalid": "页脚文字最多 {max} 个字符，且不能含控制字符",
  "branding.image_dimensions": "图片尺寸不能超过 {max}×{max} 像素",
  "branding.image_not_png": "只支持 PNG 图片",
  "branding.image_too_large": "图片不能超过 {max_kib} KiB",
  "branding.label_invalid": "链接文字须为 1–{max} 个字符的一行文字",
  "branding.platform_invalid": "未知的客户端平台",
  "branding.too_many_downloads": "客户端下载链接最多 {max} 个",
  "branding.too_many_links": "页脚链接最多 {max} 个",
  "branding.url_invalid": "链接须以 https://、http:// 或 / 开头",
  "branding.version_conflict": "设置已被修改（可能是其他管理员），请刷新后重试",
  "kb.category_unknown": "所选分类不存在（可能已被删除），请刷新后重试",
  "kb.name_long": "分类名称不能超过 {max} 个字符",
  "kb.name_multiline": "分类名称只能是一行",
  "kb.name_required": "请填写分类名称",
  "kb.sort_range": "排序值须在 ±{max} 之间",
  "kb.slug_invalid": "固定地址只能用 1–{max} 个小写字母、数字或 -（不能以 - 开头）",
  "kb.slug_taken": "另一篇文章已经使用这个固定地址",
  "mail_template.body_control": "正文不能含控制字符",
  "mail_template.body_length": "正文须为 1–{max} 个字符",
  "mail_template.kind_unknown": "未知的邮件种类：{kind}",
  "mail_template.locale_invalid": "语言只能是中文或英文",
  "mail_template.placeholder_missing": "模板必须包含占位符 {{name}}",
  "mail_template.placeholder_unknown": "未知占位符 {{name}}（只能使用列出的占位符）",
  "mail_template.subject_length": "主题须为 1–{max} 个字符",
  "mail_template.subject_multiline": "主题只能是一行",
  "mail_template.version_conflict": "模板已被修改（可能是其他管理员），请刷新后重试",
  // 告警
  "alert.channel_invalid": "通知通道只能是 Telegram、Webhook 或邮件",
  "alert.email_invalid": "邮件收件人地址无效：{e}",
  "alert.email_needs_recipient": "邮件通知至少需要一个收件人",
  "alert.email_unavailable": "邮件发送尚未配置，请先在「系统设置 → 邮件」配置 SMTP",
  "alert.field_range": "{field} 须在 {lo}–{hi} 之间",
  "alert.kind_unknown": "未知的告警类型：{k}",
  "alert.retry_not_failed": "只有发送失败的通知可以重试",
  "alert.status_invalid": "状态只能是「告警中」或「已恢复」",
  "alert.telegram_api_url_invalid": "Telegram API 地址须为 https 源站（如 https://tg.example.com，不含路径）",
  "alert.telegram_chat_invalid": "Telegram 聊天 ID 须为数字 ID 或 @频道名",
  "alert.telegram_chat_missing": "Telegram 通知需要填写聊天 ID",
  "alert.telegram_token_invalid": "Telegram Bot Token 格式不正确（形如 123456789:AA…，从 @BotFather 获取）",
  "alert.telegram_token_missing": "Telegram 通知需要 Bot Token",
  "alert.too_many_kinds": "关闭的告警类型过多",
  "alert.too_many_recipients": "邮件收件人最多 5 个",
  "alert.webhook_secret_invalid": "Webhook 签名密钥须为 16–128 个可打印 ASCII 字符",
  "alert.webhook_secret_missing": "Webhook 需要签名密钥",
  "alert.webhook_url_invalid": "Webhook 地址无效：{m}",
  "alert.webhook_url_missing": "Webhook 需要填写地址",
  // 批量操作（运营）
  "batch.body_length": "邮件正文须为 1–{max_body} 个字符",
  "batch.empty": "没有选中任何用户",
  "batch.finished": "该任务已经结束，不能取消",
  "batch.mail_unavailable": "邮件发送尚未配置或已关闭，请先在「系统设置 → 邮件」配置 SMTP",
  "batch.selection_invalid": "请选择用户，或使用当前筛选条件（二选一）",
  "batch.subject_invalid": "邮件标题须为 1–{max_subject} 个字符，且不能含换行",
  "batch.too_many_ids": "按勾选批量操作最多 {max_ids} 个用户，更多请使用筛选条件",
  // 批量优惠码
  "coupon_batch.code_space": "优惠码重复过多，请加长随机部分或更换前缀",
  "coupon_batch.count_range": "数量须为 1–{max_count}",
  "coupon_batch.length_range": "随机部分长度须为 {min_len}–{max_len}",
  "coupon_batch.prefix_invalid": "前缀最多 {max_prefix} 个字符（字母、数字、- 或 _）",
  "coupon_batch.revoked": "该批次已作废",
  // 入口
  "entrance.host_invalid": "连接地址须为域名或 IP 地址",
  "entrance.name_invalid": "入口名称须为 1–{max} 个可打印字符",
  "entrance.port_invalid": "连接端口须为 1–65535",
  "entrance.direct_permanent": "直连入口不能删除，可以停用",
  "entrance.listen_port_invalid": "监听端口须为 1–65535",
  "entrance.name_exists": "该节点已有同名入口",
  "entrance.port_clash": "端口冲突：{detail}",
  "entrance.rate_invalid": "倍率须在 0–100 之间，最多 3 位小数",
  "entrance.rate_rule_invalid": "时段倍率规则无效：第 {index} 条（{detail}）",
  "entrance.rate_rules_too_many": "每个入口最多 {max} 条时段倍率规则",
  "entrance.relay_address": "中转入口必须填写连接地址与连接端口",
  "entrance.relay_only": "监听端口与来源 IP 只属于中转入口",
  "entrance.source_invalid": "中转出口 IP 无效：{detail}",
  "entrance.too_many": "该节点的入口编号已用尽",
  // 导出
  "export.group_invalid": "分组只能是按日或按节点",
  "export.range_invalid": "开始日期不能晚于结束日期",
  "export.range_too_long": "日期范围不能超过 {max_range_days} 天",
  "export.via_invalid": "未知的付款方式",
  // 优惠券
  "coupon_admin.code_exists": "已存在相同的优惠码（不区分大小写）",
  "coupon_admin.code_invalid": "优惠码须为 {min_code}–{max_code} 个字符（字母、数字、_ 或 -）",
  "coupon_admin.ends_before_starts": "失效时间必须晚于生效时间",
  "coupon_admin.fixed_range": "固定金额须在 0.01–{max_price_yuan} 元之间",
  "coupon_admin.in_use": "该优惠码已被订单使用，不能删除，请改为停用",
  "coupon_admin.limit_range": "使用次数上限须为 1–{max_limit}（留空不限）",
  "coupon_admin.max_uses_below_used": "总次数上限不能低于已使用的 {used} 次",
  "coupon_admin.min_amount_range": "最低消费须在 0–{max_price_yuan} 元之间",
  "coupon_admin.name_long": "名称最多 {max_name} 个字符",
  "coupon_admin.percent_range": "折扣百分比须为 1–100",
  "coupon_admin.periods_empty": "适用时长至少选一个（不限请留空）",
  "coupon_admin.plans_range": "适用套餐须为 1–{max_scope_plans} 个（不限请留空）",
  "coupon_admin.unknown_plan": "适用套餐中有不存在的套餐",
  // 资金
  "finance.adjust_range": "调整金额不能为 0，且绝对值不超过 {max_adjust_yuan} 元",
  "finance.hold_days_range": "冻结天数须为 0–{max_hold_days}",
  "finance.min_withdrawal_range": "最低提现金额须在 0.01–{max_price_yuan} 元之间",
  "finance.rate_percent_range": "返利比例须为 0–100",
  "finance.usdt_chain_unknown": "未知的 USDT 网络 {chain}",
  "finance.usdt_rate_range": "参考汇率须为每 1 USDT 0.01–10000 元",
  "finance.withdrawal_user_gone": "该用户已删除，只能标记为已打款",
  // 节点组
  "group.description_long": "说明最多 {max_description} 个字符",
  "group.name_exists": "已存在同名的节点组",
  "group.unknown": "节点组不存在（可能已被删除）",
  // 入站
  "inbound.account_invalid": "入站无法生成用户凭据：{detail}",
  "inbound.fakedns": "入站：agent 不支持 fakedns",
  "inbound.invalid": "入站无效：{detail}",
  "inbound.not_object": "入站配置必须是 JSON 对象",
  "inbound.protocol_missing": "入站缺少协议（protocol）",
  // 安装
  "install.origin_invalid": "面板地址无效：{e}",
  "install.origin_required": "缺少面板地址：请先在「系统设置」填写主域名",
  // 邮件
  "mail.api_key_invalid": "API 密钥无效",
  "mail.credentials_need_tls": "为保护密码，SMTP 账号只能通过 TLS 发送（加密方式选 STARTTLS 或 TLS）",
  "mail.enable_needs_api_key": "启用发信前请填写 API 密钥与发件地址",
  "mail.enable_needs_host": "启用发信前请填写 SMTP 服务器与发件地址",
  "mail.expiry_days_range": "到期提醒天数须为 0–30",
  "mail.from_invalid": "发件地址不是有效的邮箱地址",
  "mail.from_name_long": "发件人名称最多 64 个字符",
  "mail.host_invalid": "SMTP 服务器须为主机名或 IP 地址",
  "mail.password_invalid": "SMTP 密码无效",
  "mail.provider_invalid": "不支持的发信方式",
  "mail.retry_not_dead": "只能重试尚未过期的失败邮件",
  "mail.security_invalid": "加密方式只能是 STARTTLS、TLS 或无",
  "mail.status_invalid": "状态只能是失败、待发送或已发送",
  "mail.test_failed": "测试邮件发送失败：{detail}",
  "mail.test_needs_host": "请先保存 SMTP 服务器和发件地址",
  "mail.to_invalid": "收件地址不是有效的邮箱地址",
  "mail.username_invalid": "SMTP 用户名无效",
  // 服务器（Q1：一台机器 = 一个 agent）
  "server.deleting": "服务器正在删除，不能修改",
  "server.name_exists": "已存在同名的服务器",
  "server.name_invalid": "服务器名称须为 1–64 个字符，不能含控制字符",
  "server.quota_invalid": "流量额度须大于 0（留空 = 不限）",
  "server.quota_mode_invalid": "计费方式须为 双向 / 仅上行 / 仅下行",
  "server.reset_day_invalid": "重置日须为 1–31（留空 = 不重置）",
  // 节点
  "node.acme_agent_too_old":
    "该服务器的 agent 版本过旧（协议 {p} < {need}），不支持自动证书：请先升级 agent（升级发布，或在服务器上重新运行一次安装命令），或清空服务器域名并手动放置证书",
  "node.display_name_invalid": "显示名称最多 {max_display_chars} 个可打印字符",
  "node.max_rate_invalid": "计费速率上限必须大于 0",
  "node.name_empty": "节点名称不能为空",
  "node.name_exists": "已存在同名的节点",
  "node.name_invalid": "节点名称须为 1–64 个字符，不能含控制字符",
  "node.probe_cooldown": "刚刚已经请求过测速，请稍后再试",
  "node.range_invalid": "时间范围只能是 1h、6h、24h、48h、7d、30d、90d",
  "node.region_long": "地区最多 64 个字符",
  "node.server_fields": "服务器域名与安装链接属于服务器：在服务器上修改",
  "node.template_and_inbound": "模板与入站 JSON 只能二选一",
  "node.sort_range": "排序值须在 -{sort_limit} 到 {sort_limit} 之间",
  "node.tag_invalid": "每个标签最多 {max_tag_chars} 个可打印字符，且不能含「|」",
  "node.tls_domain_invalid": "节点域名须为形如 node1.example.com 的域名（不能是 IP 或通配符）",
  "node.too_many_tags": "标签最多 {max_tags} 个",
  "node.view_invalid": "视图参数只能是 summary 或 full",
  // 订单（后台）
  "order_admin.already_fulfilled": "该订单已开通",
  "order_admin.already_refunded": "该订单已退款",
  "order_admin.manual_not_fulfilled": "套餐无法开通，人工订单未创建：{error}",
  "order_admin.no_price": "该套餐没有这个周期的价格，请先在「套餐」页定价",
  "order_admin.plan_gone": "套餐已不存在",
  "order_admin.refund_external_range": "支付宝后台退款金额须为 0–{amount_cents} 分（不超过实付金额）",
  "order_admin.refund_external_required": "请填写在支付宝商家后台实际退款的金额",
  "order_admin.refund_external_with_balance": "已选择退到余额，不能再填写支付宝后台退款金额",
  "order_admin.refund_not_paid": "只有已付款的订单可以退款",
  "order_admin.refund_user_gone": "用户已删除：请线下退款，不要选择「退回余额」",
  "order_admin.refunded": "该订单已退款，不能再开通",
  "order_admin.superseded": "下单后用户已另购或更换套餐：迟到的付款不替换当前套餐（已自动退回余额）",
  "order_admin.user_gone": "用户已不存在",
  "order_admin.user_has_pending": "该用户有待付款订单，请先取消或等待其结束",
  // 套餐
  "plan.capacity_negative": "库存不能为负数",
  "plan.description_control": "说明不能包含控制字符",
  "plan.description_long": "说明最多 {max_plan_description} 个字符",
  "plan.disabled": "该套餐已停用，不能分配",
  "plan.in_use": "有 {active} 个用户正在使用此套餐：请先为他们更换或取消套餐（或改为停用此套餐）",
  "plan.name_exists": "已存在同名的套餐",
  "plan.name_length": "名称须为 1–{max_name} 个字符",
  "plan.on_sale_needs_price": "上架的套餐至少需要一个流量重置包以外的价格",
  "plan.period_invalid": "流量重置周期无效（每月 / 不重置 / 每 1–{max_period_days} 天）",
  "plan.price_days_missing": "「自定义天数」需要填写天数",
  "plan.price_days_range": "天数须为 1–{max_period_days}",
  "plan.price_days_unexpected": "该周期（{period}）不需要填写天数",
  "plan.price_duplicate": "同一周期（{period}）只能有一个价格",
  "plan.price_range": "价格须在 0.01–{max_price_yuan} 元之间",
  "plan.quota_negative": "流量额度不能为负数",
  "plan.seats_negative": "设备数不能为负数",
  "plan.speed_limit_range": "限速须为 1–{max_speed_mbps} Mbps",
  "plan.unknown": "套餐不存在（可能已被删除）",
  "plan.unknown_ref": "选择的{what}不存在（可能已被删除）",
  // 发布与灰度更新
  "release.binary_exists": "该发布的程序文件已上传",
  "release.binary_mismatch": "程序文件与签名清单不符（{total} 字节，sha256 {sha}）",
  "release.binary_too_large": "程序文件超过清单声明的 {size} 字节",
  "release.exists": "相同版本/平台或相同摘要的发布已存在",
  "release.manifest_invalid": "发布清单无效：{detail}",
  "release.no_keys": "面板没有可用的发布公钥（系统设置 → 安全），自动更新已关闭",
  "release.panel_too_old": "该版本需要面板协议 {needed}（当前面板为 {have}），请先升级面板",
  "release.rollout_open": "有未结束的灰度更新使用此版本，请先中止",
  "release.signature_invalid": "签名校验失败：{detail}",
  "release.upload_interrupted": "上传中断，请重试",
  "rollout.another_open": "已有一个未结束的灰度更新，请先完成或中止它",
  "rollout.bad_node": "所选节点中有不存在、未注册或正在删除的节点",
  "rollout.bad_transition": "当前状态（{status}）不能执行此操作",
  "rollout.failure_ratio_range": "失败比例须在 0–1 之间",
  "rollout.no_nodes": "没有可更新的已注册节点",
  "rollout.no_release": "还没有上传该版本（先上传清单、签名与程序文件）",
  "rollout.percentage_range": "百分比须为 1–100",
  "rollout.timeout_range": "健康检查超时须为 30–86400 秒",
  "rollout.version_invalid": "版本号格式应为 vMAJOR.MINOR.PATCH[-pre]",
  "rollout.waves_invalid": "分批设置无效：{detail}",
  // 系统设置 → 支付（W24/R40）
  "payments.app_id_invalid": "APPID 须为 1–32 位数字",
  "payments.config_invalid": "配置格式错误",
  "payments.config_unknown_field": "未知的配置项：{field}",
  "payments.environment_invalid": "环境须为 沙箱 / 正式 / 自定义网关",
  "payments.gateway_invalid": "自定义网关须为 https 地址（http 仅限本机回环）",
  "payments.gateway_unexpected": "只有「自定义网关」环境才能填写网关地址",
  "payments.icon_invalid": "图标须为 1–32 个小写字母、数字、- 或 _",
  "payments.incomplete": "配置不完整：启用前请填写 APPID、应用私钥与支付宝公钥",
  "payments.kind_immutable": "支付方式的类型不能修改，请新增一个",
  "payments.kind_unknown": "未知的支付方式类型：{kind}",
  "payments.method_in_use": "已有订单使用该支付方式，不能删除（可以停用）",
  "payments.name_invalid": "名称须为 1–64 个字符，不能含控制字符",
  "payments.not_configured": "请先保存完整的配置再测试连接",
  "payments.private_key_invalid": "应用私钥无效：请粘贴 RSA 私钥（PEM 或支付宝密钥工具生成的 base64）",
  "payments.private_key_too_short": "应用私钥太短：RSA2 需要至少 2048 位",
  "payments.public_key_invalid": "支付宝公钥无效：请粘贴 RSA 公钥（PEM 或 base64）",
  "payments.public_key_is_app_key": "填写的是应用公钥，不是支付宝公钥：请在支付宝开放平台复制「支付宝公钥」",
  "payments.public_key_is_private": "支付宝公钥一栏填入的是私钥：请改填支付宝公钥（不要外泄私钥）",
  "payments.public_key_too_short": "支付宝公钥太短：RSA2 需要至少 2048 位",
  "payments.seller_id_invalid": "商户 PID 须为数字（2088 开头）",
  "payments.sort_range": "排序值须在 ±1000000 之内",
  "payments.stored_key_unreadable": "已保存的密钥无法解密（data/master.key 已更换？）：请重新粘贴",
  "payments.timeout_range": "订单有效期须为 5–120 分钟",
  // 系统设置
  "settings.acme_email_invalid": "ACME 邮箱：不是有效的邮箱地址（可留空）",
  "settings.acme_url_invalid": "ACME 目录：必须是 https:// 地址（留空 = Let's Encrypt）",
  "settings.audit_retention_invalid": "审计日志保留天数：0（永久）到 36500",
  "settings.cloudflare_range_invalid": "Cloudflare 网段：{range} 不是有效的 CIDR",
  "settings.cloudflare_ranges_too_many": "Cloudflare 网段：最多 {max} 条",
  "settings.confirm_required": "需要确认后才能执行",
  "settings.domain_invalid": "{field}：{e}",
  "settings.fallback_url_invalid": "备用下载地址：必须是含 {arch} 的 https:// 地址，不能有引号、空格或 shell 特殊字符",
  "settings.host_gate":
    "保存后面板只接受主域名/订阅域名（以及 IP 地址）的访问，当前访问地址 {host} 将被拒绝。请确认主域名已解析并能打开，再勾选确认后保存。",
  "cleanup.after_days_range": "未使用天数须为 1–3650",
  "cleanup.warn_days_range": "提醒后等待天数须为 1–90",
  "settings.domain_conflict": "{domain} 不能同时是{a}和{b}（一个域名只能有一种用途）",
  "settings.domain_duplicate": "{kind}：{domain} 重复",
  "settings.domain_removal_unconfirmed": "删除域名 {domains} 前需要先确认影响",
  "settings.domains_too_many": "{kind}最多 {max} 个",
  "settings.node_domain_cloudflare": "{detail}",
  "settings.node_domain_unset": "节点通信域名未设置：请先在「系统设置 → 节点通信」填写节点连接面板所用的域名或 IP",
  "settings.node_domain_unspecified": "节点通信域名：不能是 0.0.0.0 / ::",
  "settings.probe_interval_range": "测速间隔：须在 600 秒（10 分钟）到 604800 秒（7 天）之间",
  "settings.probe_url_duplicate": "测速地址：不能重复",
  "settings.probe_url_invalid": "测速地址：{bad} 不是有效的 http(s) 地址（不能含空白或用户名）",
  "settings.probe_urls_too_many": "测速地址：最多 4 个",
  "settings.release_key_invalid": "额外信任的发布公钥：{detail}（每行一个「base64 公钥 标签」）",
  "settings.release_keys_too_many": "额外信任的发布公钥：最多 {max} 个",
  "settings.server_name_locked": "{detail}",
  "settings.timezone_invalid": "未知的时区「{tz}」（请填写 IANA 名称，如 Asia/Shanghai）",
  "settings.site_name_invalid": "站点名称须为 1–{max} 个字符，不能含控制字符",
  "settings.sub_format_invalid": "未知的订阅格式：{value}（clash、sing-box、links）",
  "settings.sub_import_client_invalid": "未知的导入客户端：{value}（clash、stash、shadowrocket、sing-box、hiddify）",
  "settings.sub_rule_invalid": "分流规则无效：第 {index} 条（{detail}）",
  "settings.sub_rule_set_url_invalid": "规则列表地址须为 https，并包含 {name}（可选 {kind}）",
  "settings.sub_rules_too_many": "分流规则最多 {max} 条",
  "settings.tls_pin_invalid": "安装命令公钥钉扎：格式应为 sha256//<base64>（留空 = 自动探测）",
  "settings.traffic_retention_invalid": "流量明细保留天数：0（永久）或 32 到 36500",
  "settings.allowlist_excludes_you": "名单里没有你当前的地址 {ip}：保存后你会立即无法访问后台",
  "settings.allowlist_invalid": "{value} 不是有效的 IP 地址或 CIDR 网段",
  "settings.allowlist_too_long": "白名单最多 {max} 条",
  "settings.path_invalid": "只能使用 {min}–64 个字母、数字、- 或 _",
  "settings.path_reserved": "{value} 已被门户使用，请换一个",
  "settings.path_taken": "这个值已被后台前缀或订阅路径使用",
  "settings.version_conflict": "设置已被修改（可能是其他管理员），请刷新后重试",
  "auth_admin.min_submit_range": "最短提交时间须为 0–60 秒",
  "auth_admin.turnstile_incomplete": "启用 Turnstile 需要同时设置站点密钥与密钥",
  "auth_admin.turnstile_key_invalid": "Turnstile 站点密钥格式无效",
  "auth_admin.turnstile_secret_invalid": "Turnstile 密钥格式无效",
  "signup_admin.domain_invalid": "邮箱域名无效：{d}",
  "signup_admin.invites_range": "每人邀请码数量须为 0–100",
  "signup_admin.mail_off": "请先在「系统设置 → 邮件」启用发信",
  "signup_admin.needs_main_domain": "请先设置主域名：找回密码链接需要它",
  "signup_admin.too_many_domains": "邮箱域名最多 100 个",
  "signup_admin.trial_days_range": "试用天数须为 1–3650",
  "signup_admin.unknown_trial_plan": "试用套餐不存在",
  // 入站模板
  "template.dest_invalid": "目标站点须为域名（可带 :端口）",
  "template.dest_port": "目标端口须为 1–65535",
  "template.domain_invalid": "{what} 须为节点证书的域名",
  "template.domain_mismatch": "{what} {d} 与节点域名 {n} 不同：自动证书只覆盖 {n}（留空即使用节点域名）",
  "template.domain_missing": "{what}：请设置节点域名，或为此入站填写域名",
  "template.fingerprint_invalid": "指纹只能是：{allowed}",
  "template.method_invalid": "加密方式只能是：{allowed}",
  "template.mode_invalid": "XHTTP 模式只能是：{allowed}",
  "template.needs_tls": "Trojan 与 gRPC 需要 TLS（开启 TLS 并设置节点域名，或填写证书域名）",
  "template.network_invalid": "传输方式只能是 WebSocket、HTTPUpgrade、XHTTP 或 gRPC",
  "template.path_invalid": "路径须以 / 开头，只含字母、数字和 /-_.~（不超过 128 个字符）",
  "template.port_clash": "端口 {p} 已被其他入站占用",
  "template.protocol_invalid": "协议只能是 VLESS、VMess 或 Trojan",
  "template.service_name_invalid": "gRPC 服务名只能含字母、数字和 -_.（不超过 64 个字符）",
  "template.tls_domain_without_tls": "未开启 TLS 却填写了证书域名",
  // 工单（客服）
  "ticket_admin.assignee_filter": "负责人筛选只能是「我」「未分配」或某个管理员",
  "ticket_admin.assignee_invalid": "负责人必须是已启用的管理员",
  "ticket_admin.not_closed": "工单未关闭",
  "ticket_admin.search_long": "搜索内容最多 64 个字符",
  "ticket_admin.status_invalid": "状态筛选无效",
  // 用户
  "user.admin_no_subscription": "管理员账户没有订阅链接",
  "user.admin_no_plan": "管理员账户不是代理用户，不能分配套餐",
  "user.email_exists": "已有其他账户使用这个邮箱",
  "user.has_plan": "该用户有生效中的套餐：请先取消套餐，再设为管理员",
  "user.delete_confirm_required": "删除用户前需要先确认影响（余额、提现、订单、套餐）",
  "user.bulk_delete_changed": "删除范围已变化：请重新预览数量后再确认",
  "user.bulk_delete_too_many": "一次最多删除 {max} 个账号：请缩小范围",
  "user.date_filter_invalid": "{field}：日期格式应为 YYYY-MM-DD",
  "user.erase_admin": "管理员账号不能注销：请先降级",
  "user.erased": "该账号已注销（匿名化保留），不能再修改",
  "user.owner_already": "该账号已经是所有者",
  "user.owner_confirm_required": "转让所有者需要二次确认",
  "user.owner_only": "只有所有者可以执行此操作（管理其他管理员、后台前缀与白名单、支付渠道密钥）",
  "user.owner_protected": "所有者不能被降级、封禁或删除：请先把所有者转让给另一位管理员",
  "user.owner_target": "只能转让给已启用的管理员",
  "user.promote_banned": "该账号已被封禁：请先解封，再设为管理员",
  "user.ban_reason_required": "请填写封禁原因（会显示给用户）",
  "user.ban_reason_too_long": "封禁原因最多 {max} 个字符",
  "user.ban_self": "不能封禁自己的账户",
  "user.not_banned": "该账户没有被封禁",
  "user.plan_filter_invalid": "套餐筛选无效",
  "user.query_too_long": "搜索内容最多 {max} 个字符",
  "user.role_invalid": "角色只能是用户或管理员",
  "user.sort_invalid": "排序方式无效",
  "user.status_filter_invalid": "状态筛选无效",
  "user_plan.confirm_required": "重置流量需要确认",
  "user_plan.extend_days_range": "延长天数须为 1–{max_period_days}",
  "user_plan.extend_onetime": "一次性套餐不能按天延长：请续期一个时长或重新分配套餐",
  "user_plan.no_expiry": "该订阅没有到期时间，无需续期",
  "user_plan.none": "该用户没有生效的套餐",
  "user_plan.renew_mode": "续期请选择「续期一个时长」或「延长 N 天」之一",
  "user_plan.term_days_missing": "「自定义天数」需要填写天数",
  "user_plan.term_days_range": "天数须为 1–{max_period_days}",
  "user_plan.term_days_unexpected": "该时长不需要天数",
  "user_plan.term_reset": "流量重置包不是套餐时长",
};

// Stored server messages without a code (orders' fulfil_error, rows
// written before W21) the console still shows: English -> Chinese.
const ADMIN_MESSAGES: Record<string, string> = {
  "the plan no longer exists": "套餐已不存在",
  "plan is sold out": "套餐已售罄",
  "plan is disabled (not offered)": "套餐已停用",
  "the user no longer exists": "用户已不存在",
  "insufficient balance": "余额不足",
  "admin accounts are not proxy users and cannot have a plan": "管理员账户不能持有套餐",
};

function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, name: string) => (name in vars ? String(vars[name]) : m));
}

/** Chinese text of a stored server message (fulfil_error etc.); itself when unknown. */
export function adminMessageText(message: string): string {
  return ADMIN_MESSAGES[message] ?? message;
}

// Like zh, but an unknown server message stays bare (no "操作失败：" wrapper),
// for callers that put their own context in front.
const zhBare: typeof zh = (key, vars) => (key === "errors.generic" ? String(vars?.message ?? "") : zh(key, vars));

/**
 * errorText for the admin console (Chinese only, R18), usable outside
 * components. With `context` the text is "<context>：<detail>" (one prefix,
 * not "<context>：操作失败：<detail>").
 */
export function adminErrorText(err: unknown, context?: string): string {
  let text: string | undefined;
  if (err instanceof ApiError) {
    const own = ADMIN_CODES[err.code];
    if (own) text = fill(own, errorVars(err.params, err.message));
    else if (!CODE_KEYS[err.code] && ADMIN_MESSAGES[err.message]) text = ADMIN_MESSAGES[err.message];
  }
  text ??= errorText(err, context ? zhBare : zh);
  return context ? `${context}：${text}` : text;
}
