// Server error codes (src/error_codes.txt) → zh / en text. `{name}` = the
// error's params (plus `<p>_yuan` for each `<p>_cents`).
// scripts/check-error-codes.mjs keeps this equal to the registry.
export const ERRORS: Record<string, [zh: string, en: string]> = {
  "account.banned": ["账户已被封禁", "This account is banned."],
  "account.delete_confirm_required": ["注销账号需要确认", "Deleting the account needs a confirmation."],
  "account.delete_pending_orders": ["有待付款的订单：请先取消订单再注销", "There is an unpaid order: cancel it before deleting the account."],
  "account.delete_pending_withdrawals": ["有待处理的提现：请先取消提现再注销", "There is a pending withdrawal: cancel it before deleting the account."],
  "account.invalid_password": ["当前密码不正确", "The current password is not correct."],
  "account.locale_invalid": ["不支持的语言", "Unsupported language"],
  "account.mail_off": ["邮件服务未启用，请联系管理员", "Email is not available. Contact the administrator."],
  "account.passkey_exists": ["这个通行密钥已经绑定过", "This passkey is already registered"],
  "account.passkey_failed": ["通行密钥验证失败，请重试", "The passkey could not be verified, please try again"],
  "account.passkey_limit": ["每个账户最多 {max} 个通行密钥", "At most {max} passkeys per account"],
  "account.passkey_name_invalid": ["名称须为 1–{max} 个字符", "The name must be 1–{max} characters"],
  "account.passkey_required": ["请先绑定一个通行密钥，再关闭密码登录", "Add a passkey before turning off password sign-in"],
  "account.passkey_unavailable": ["本站暂不支持通行密钥（需要 https 主域名）", "Passkeys are not available on this site (needs an https main domain)"],
  "account.password_required": ["请输入当前密码", "Enter your current password."],
  "account.password_too_long": ["密码过长", "The password is too long"],
  "account.password_too_short": ["密码至少需要 8 位", "The password must be at least 8 characters"],
  "agent_update.asset_missing": ["发布 {version} 缺少文件 {name}（发布未签名或不完整）", "Release {version} has no {name}"],
  "agent_update.check_running": ["已有更新检查在进行中，请稍候", "An update check is already running"],
  "agent_update.checksum_mismatch": ["{name} 与 SHA256SUMS 不符，已拒绝", "{name} does not match SHA256SUMS"],
  "agent_update.checksum_missing": ["SHA256SUMS 中没有 {name}", "SHA256SUMS does not list {name}"],
  "agent_update.checksums_invalid": ["SHA256SUMS 格式无效：{detail}", "SHA256SUMS is invalid: {detail}"],
  "agent_update.downgrade": ["发布源的最新版本 {latest} 低于面板已有的 {have}，拒绝降级", "The source's latest release {latest} is older than the stored {have}: refusing to go back"],
  "agent_update.fetch_failed": ["下载 {what} 失败：{detail}", "Fetching {what} failed: {detail}"],
  "agent_update.host_not_allowed": ["{what} 位于发布源之外的主机 {host}，已拒绝", "{what}: host {host} is not the configured source"],
  "agent_update.http_status": ["下载 {what} 失败：HTTP {status}", "Fetching {what}: HTTP {status}"],
  "agent_update.platform_mismatch": ["{name} 的平台是 {os}/{arch}，与文件名不符", "{name} is for {os}/{arch}"],
  "agent_update.prerelease": ["发布源的最新发布 {version} 是草稿或预发布版本，未保存", "The source's latest release {version} is a draft or pre-release"],
  "agent_update.release_invalid": ["发布源返回的发布信息无效：{detail}", "The source's release is invalid: {detail}"],
  "agent_update.rollback_refused": ["{name} 是回滚清单，不会自动保存；如确需回滚请手动上传", "{name} is a rollback manifest: upload it by hand if that is intended"],
  "agent_update.size_mismatch": ["{name} 大小为 {got} 字节，与清单声明的 {want} 字节不符", "{name} is {got} bytes, its manifest says {want}"],
  "agent_update.source_invalid": ["发布源地址无效：{detail}（须为 HTTPS）", "Source URL must be 8–512 characters"],
  "agent_update.timed_out": ["更新检查超时，请稍后重试", "The update check took too long"],
  "agent_update.too_large": ["{what} 超过 {max} 字节上限", "{what} is larger than {max} bytes"],
  "agent_update.version_mismatch": ["{name} 的版本是 {got}，与发布 {version} 不符", "{name} is version {got}, the release is {version}"],
  "alert.channel_invalid": ["通知通道只能是 Telegram、Webhook 或邮件", "Channel must be telegram, webhook or email"],
  "alert.email_invalid": ["邮件收件人地址无效：{e}", "Invalid email address {e}"],
  "alert.email_needs_recipient": ["邮件通知至少需要一个收件人", "Email needs at least one recipient"],
  "alert.email_unavailable": ["邮件发送尚未配置，请先在「系统设置 → 邮件」配置 SMTP", "Email delivery is not available yet (configure SMTP first)"],
  "alert.field_range": ["{field} 须在 {lo}–{hi} 之间", "{field} must be {lo}-{hi}"],
  "alert.kind_unknown": ["未知的告警类型：{k}", "Unknown alert kind {k} (one of: {allowed})"],
  "alert.retry_not_failed": ["只有发送失败的通知可以重试", "Only failed deliveries can be retried"],
  "alert.status_invalid": ["状态只能是「告警中」或「已恢复」", "Status must be firing or resolved"],
  "alert.telegram_api_url_invalid": ["Telegram API 地址须为 https 源站（如 https://tg.example.com，不含路径）", "Telegram_api_url must be an https origin such as https://tg.example.com"],
  "alert.telegram_chat_invalid": ["Telegram 聊天 ID 须为数字 ID 或 @频道名", "Telegram_chat_id must be a numeric chat id or @channel"],
  "alert.telegram_chat_missing": ["Telegram 通知需要填写聊天 ID", "Telegram needs a chat id"],
  "alert.telegram_token_invalid": ["Telegram Bot Token 格式不正确（形如 123456789:AA…，从 @BotFather 获取）", "Telegram_token must look like 123456789:AA... (from @BotFather)"],
  "alert.telegram_token_missing": ["Telegram 通知需要 Bot Token", "Telegram needs a bot token"],
  "alert.too_many_kinds": ["关闭的告警类型过多", "Too many disabled kinds"],
  "alert.too_many_recipients": ["邮件收件人最多 5 个", "At most 5 email recipients"],
  "alert.webhook_secret_invalid": ["Webhook 签名密钥须为 16–128 个可打印 ASCII 字符", "Webhook_secret must be 16-128 printable ASCII characters"],
  "alert.webhook_secret_missing": ["Webhook 需要签名密钥", "The webhook needs a signing secret"],
  "alert.webhook_url_invalid": ["Webhook 地址无效：{m}", "Webhook_url: {m}"],
  "alert.webhook_url_missing": ["Webhook 需要填写地址", "The webhook needs a URL"],
  "announcement.audience_invalid": ["受众只能是全部用户、有生效套餐的用户或没有套餐的用户", "Audience must be one of: {allowed}"],
  "announcement.body_long": ["正文不能超过 {max} 个字符", "Body is longer than {max} characters"],
  "announcement.body_required": ["请填写正文", "Body is required"],
  "announcement.mail_in_progress": ["这条公告正在发送邮件，完成后才能再次发送", "This announcement is being mailed right now"],
  "announcement.mail_unavailable": ["邮件发送尚未配置，请先在「系统设置 → 邮件」配置并启用 SMTP", "Email sending is not configured (Settings → Mail)"],
  "announcement.title_long": ["标题不能超过 {max} 个字符", "Title is longer than {max} characters"],
  "announcement.title_multiline": ["标题只能是一行", "Title must be a single line"],
  "announcement.title_required": ["请填写标题", "Title is required"],
  "announcement.window_invalid": ["开始显示时间必须早于结束显示时间", "Visible_from must be before visible_until"],
  "auth.captcha_failed": ["人机验证未通过，请重试", "Human verification failed, please try again"],
  "auth.captcha_unavailable": ["人机验证服务暂不可用，请稍后再试", "Human verification is unavailable, try again later"],
  "auth.credentials_required": ["请填写账号和密码", "Enter your account and password"],
  "auth.forbidden": ["没有权限执行此操作", "You are not allowed to do this."],
  "auth.passkey_required": ["此账户只能使用通行密钥登录", "This account signs in with a passkey"],
  "auth.unauthorized": ["登录已失效，请重新登录", "Your session has ended. Please sign in again."],
  "auth_admin.min_submit_range": ["最短提交时间须为 0–60 秒", "Min_submit_secs must be 0-60"],
  "auth_admin.turnstile_incomplete": ["启用 Turnstile 需要同时设置站点密钥与密钥", "Turnstile needs both the site key and the secret before a form can use it"],
  "auth_admin.turnstile_key_invalid": ["Turnstile 站点密钥格式无效", "The Turnstile site key must be 1-128 characters of [A-Za-z0-9_-]"],
  "auth_admin.turnstile_secret_invalid": ["Turnstile 密钥格式无效", "The Turnstile secret is not a valid key"],
  "balance.admin_none": ["管理员账户没有余额", "Admin accounts have no balance"],
  "balance.insufficient": ["余额不足", "Insufficient balance."],
  "batch.body_length": ["邮件正文须为 1–{max_body} 个字符", "Body must be 1-{max_body} characters"],
  "batch.empty": ["没有选中任何用户", "No users selected"],
  "batch.finished": ["该任务已经结束，不能取消", "The batch has already finished ({status})"],
  "batch.mail_unavailable": ["邮件发送尚未配置或已关闭，请先在「系统设置 → 邮件」配置 SMTP", "Email is not configured or disabled (Settings → Mail)"],
  "batch.selection_invalid": ["请选择用户，或使用当前筛选条件（二选一）", "Give either ids or filter"],
  "batch.subject_invalid": ["邮件标题须为 1–{max_subject} 个字符，且不能含换行", "Subject must be 1-{max_subject} characters without control characters"],
  "batch.too_many_ids": ["按勾选批量操作最多 {max_ids} 个用户，更多请使用筛选条件", "At most {max_ids} users per batch by id"],
  "block_rule.builtin_fixed": ["内置规则集只能开关和排序，不能修改或删除", "Built-in rule sets can only be switched and sorted"],
  "block_rule.days_range": ["统计天数必须在 1–{max} 之间", "Days must be within 1..={max}"],
  "block_rule.entries_required": ["规则至少需要一条内容", "A rule needs at least one entry"],
  "block_rule.entry_invalid": ["第 {line} 行不是有效的条目（类型：{kind}）", "Line {line}: not a valid {kind} entry"],
  "block_rule.kind_invalid": ["规则类型必须是域名、IP 或协议", "Kind must be domain, ip or protocol"],
  "block_rule.name_long": ["规则名称最多 {max} 个字符", "Name is longer than {max} characters"],
  "block_rule.name_multiline": ["规则名称只能有一行", "Name must be a single line"],
  "block_rule.name_required": ["请填写规则名称", "Name is required"],
  "block_rule.pattern_long": ["规则内容超过 {max} 字节", "The entries exceed {max} bytes"],
  "block_rule.sort_range": ["排序值必须在 ±{max} 之内", "Sort must be within ±{max}"],
  "block_rule.too_many_entries": ["一条规则最多 {max} 条内容", "A rule holds at most {max} entries"],
  "block_rule.too_many_rules": ["自定义规则最多 {max} 条", "At most {max} custom rules"],
  "branding.footer_invalid": ["页脚文字最多 {max} 个字符，且不能含控制字符", "Footer text must be at most {max} characters"],
  "branding.image_dimensions": ["图片尺寸不能超过 {max}×{max} 像素", "Image must be at most {max}×{max} pixels"],
  "branding.image_not_png": ["只支持 PNG 图片", "Image must be a PNG"],
  "branding.image_too_large": ["图片不能超过 {max_kib} KiB", "Image is larger than {max_kib} KiB"],
  "branding.label_invalid": ["链接文字须为 1–{max} 个字符的一行文字", "Labels must be 1-{max} characters without control characters"],
  "branding.platform_invalid": ["未知的客户端平台", "Platform must be one of: {allowed}"],
  "branding.too_many_downloads": ["客户端下载链接最多 {max} 个", "At most {max} download links"],
  "branding.too_many_links": ["页脚链接最多 {max} 个", "At most {max} footer links"],
  "branding.url_invalid": ["链接须以 https://、http:// 或 / 开头", "Links must start with https://, http:// or /"],
  "branding.version_conflict": ["设置已被修改（可能是其他管理员），请刷新后重试", "The settings were changed meanwhile (perhaps by another admin); reload and retry"],
  "cleanup.after_days_range": ["未使用天数须为 1–3650", "After_days must be 1-3650"],
  "cleanup.warn_days_range": ["提醒后等待天数须为 1–90", "Warn_days must be 1-90"],
  "coupon.below_minimum": ["订单金额未达到优惠码的最低消费", "The order is below the coupon's minimum amount."],
  "coupon.expired": ["优惠码已过期", "This coupon has expired."],
  "coupon.invalid": ["优惠码无效", "Invalid coupon code."],
  "coupon.new_users_only": ["该优惠码仅限新用户首次购买", "This coupon is for new customers only."],
  "coupon.not_started": ["优惠码尚未生效", "This coupon is not valid yet."],
  "coupon.period": ["该优惠码不适用于此购买时长", "This coupon does not apply to this period."],
  "coupon.plan": ["该优惠码不适用于此套餐", "This coupon does not apply to this plan."],
  "coupon.used_up": ["优惠码已被领完", "This coupon has been used up."],
  "coupon.user_limit": ["你已使用过该优惠码", "You have already used this coupon."],
  "coupon_admin.code_exists": ["已存在相同的优惠码（不区分大小写）", "A coupon with this code already exists"],
  "coupon_admin.code_invalid": ["优惠码须为 {min_code}–{max_code} 个字符（字母、数字、_ 或 -）", "Code must be {min_code}-{max_code} characters of A-Z a-z 0-9 _ -"],
  "coupon_admin.ends_before_starts": ["失效时间必须晚于生效时间", "Ends_at must be after starts_at"],
  "coupon_admin.fixed_range": ["固定金额须在 0.01–{max_price_yuan} 元之间", "A fixed coupon's value must be 1..={max_price_cents} (integer fen)"],
  "coupon_admin.in_use": ["该优惠码已被订单使用，不能删除，请改为停用", "The coupon has been used by orders; disable it instead"],
  "coupon_admin.limit_range": ["使用次数上限须为 1–{max_limit}（留空不限）", "{field} must be 1..={max_limit} (or null for unlimited)"],
  "coupon_admin.max_uses_below_used": ["总次数上限不能低于已使用的 {used} 次", "Max_uses cannot be below the {used} uses already counted"],
  "coupon_admin.min_amount_range": ["最低消费须在 0–{max_price_yuan} 元之间", "Min_amount_cents must be 0..={max_price_cents}"],
  "coupon_admin.name_long": ["名称最多 {max_name} 个字符", "Name must be at most {max_name} characters"],
  "coupon_admin.percent_range": ["折扣百分比须为 1–100", "A percent coupon's value must be 1-100"],
  "coupon_admin.periods_empty": ["适用时长至少选一个（不限请留空）", "Periods must list at least one period (or be null for all)"],
  "coupon_admin.plans_range": ["适用套餐须为 1–{max_scope_plans} 个（不限请留空）", "Plan_ids must list 1-{max_scope_plans} plans (or be null for all)"],
  "coupon_admin.unknown_plan": ["适用套餐中有不存在的套餐", "Plan_ids contains an unknown plan"],
  "coupon_batch.code_space": ["优惠码重复过多，请加长随机部分或更换前缀", "Too many code collisions; use a longer length or another prefix"],
  "coupon_batch.count_range": ["数量须为 1–{max_count}", "Count must be 1..={max_count}"],
  "coupon_batch.length_range": ["随机部分长度须为 {min_len}–{max_len}", "Length must be {min_len}..={max_len}"],
  "coupon_batch.prefix_invalid": ["前缀最多 {max_prefix} 个字符（字母、数字、- 或 _）", "Prefix must be 0-{max_prefix} characters of A-Z a-z 0-9 _ -"],
  "coupon_batch.revoked": ["该批次已作废", "The batch is already revoked"],
  "entrance.direct_permanent": ["直连入口不能删除，可以停用", "The direct entrance cannot be deleted; disable it instead"],
  "entrance.host_invalid": ["连接地址须为域名或 IP 地址", "Connect_host must be a hostname or IP address"],
  "entrance.listen_port_invalid": ["监听端口须为 1–65535", "Listen_port must be 1-65535"],
  "entrance.name_exists": ["该节点已有同名入口", "The node already has an entrance with this name"],
  "entrance.name_invalid": ["入口名称须为 1–{max} 个可打印字符", "Bad name {name}"],
  "entrance.port_clash": ["端口冲突：{detail}", "{detail}"],
  "entrance.port_invalid": ["连接端口须为 1–65535", "Connect_port must be 1-65535"],
  "entrance.rate_invalid": ["倍率须在 0–100 之间，最多 3 位小数", "Rate must be 0-100 with at most 3 decimals"],
  "entrance.rate_rule_invalid": ["时段倍率规则无效：第 {index} 条（{detail}）", "Rule {index}: {detail}"],
  "entrance.rate_rules_too_many": ["每个入口最多 {max} 条时段倍率规则", "At most {max} rules per entrance"],
  "entrance.relay_address": ["中转入口必须填写连接地址与连接端口", "A relay entrance needs connect_host and connect_port"],
  "entrance.relay_only": ["监听端口与来源 IP 只属于中转入口", "Listen_port and source_cidrs belong to relay entrances"],
  "entrance.source_invalid": ["中转出口 IP 无效：{detail}", "Source_cidrs: {detail}"],
  "entrance.too_many": ["该节点的入口编号已用尽", "The server has used up its entrance numbers"],
  "entrance.version_conflict": ["入口已被修改（可能是其他管理员），请关闭后重新打开再保存", "The entrance was changed meanwhile (perhaps by another admin); close and reopen it, then save again"],
  "export.group_invalid": ["分组只能是按日或按节点", "Group must be day or node"],
  "export.range_invalid": ["开始日期不能晚于结束日期", "From must not be after to"],
  "export.range_too_long": ["日期范围不能超过 {max_range_days} 天", "Range longer than {max_range_days} days"],
  "export.via_invalid": ["未知的付款方式", "Unknown paid_via"],
  "finance.adjust_range": ["调整金额不能为 0，且绝对值不超过 {max_adjust_yuan} 元", "Amount_cents must be non-zero and within ±{max_adjust_cents} (integer fen)"],
  "finance.hold_days_range": ["冻结天数须为 0–{max_hold_days}", "Hold_days must be 0-{max_hold_days}"],
  "finance.min_withdrawal_range": ["最低提现金额须在 0.01–{max_price_yuan} 元之间", "Min_withdrawal_cents must be 1..={max_price_cents} (integer fen)"],
  "finance.rate_percent_range": ["返利比例须为 0–100", "Rate_percent must be 0-100"],
  "finance.usdt_chain_unknown": ["未知的 USDT 网络 {chain}", "Unknown USDT chain {chain}"],
  "finance.usdt_rate_range": ["参考汇率须为每 1 USDT 0.01–10000 元", "Usdt_rate_cents must be 1..=1000000 (CNY fen per USDT)"],
  "finance.withdrawal_user_gone": ["该用户已删除，只能标记为已打款", "The user no longer exists; approve or leave the request"],
  "group.description_long": ["说明最多 {max_description} 个字符", "Description must be at most {max_description} characters"],
  "group.name_exists": ["已存在同名的节点组", "Group name already exists"],
  "group.unknown": ["节点组不存在（可能已被删除）", "Unknown group id"],
  "inbound.account_invalid": ["入站无法生成用户凭据：{detail}", "{detail}"],
  "inbound.fakedns": ["入站：agent 不支持 fakedns", "Fakedns is not supported by the agent"],
  "inbound.invalid": ["入站无效：{detail}", "{detail}"],
  "inbound.not_object": ["入站配置必须是 JSON 对象", "Inbound must be a JSON object"],
  "inbound.protocol_missing": ["入站缺少协议（protocol）", "The inbound needs a protocol"],
  "install.origin_invalid": ["面板地址无效：{e}", "Origin: {e}"],
  "install.origin_required": ["缺少面板地址：请先在「系统设置」填写主域名", "An origin is required (or set the main domain under Settings)"],
  "invite.invalid_inviter": ["邀请关系无效", "Invalid invitation"],
  "invite.limit": ["邀请码数量已达上限，请先删除不用的邀请码", "You have reached the invite code limit. Delete an unused code first."],
  "invite.registration_closed": ["注册已关闭", "Registration is closed."],
  "kb.category_unknown": ["所选分类不存在（可能已被删除），请刷新后重试", "Unknown category"],
  "kb.name_long": ["分类名称不能超过 {max} 个字符", "Name is longer than {max} characters"],
  "kb.name_multiline": ["分类名称只能是一行", "Name must be a single line"],
  "kb.name_required": ["请填写分类名称", "Name is required"],
  "kb.query_long": ["搜索内容不能超过 {max} 个字符", "Search text must be at most {max} characters"],
  "kb.slug_invalid": ["固定地址只能用 1–{max} 个小写字母、数字或 -（不能以 - 开头）", "Slug: 1–{max} of a-z, 0-9 or - (not starting with -)"],
  "kb.slug_taken": ["另一篇文章已经使用这个固定地址", "Another article already has this slug"],
  "kb.sort_range": ["排序值须在 ±{max} 之间", "Sort must be within ±{max}"],
  "mail.api_key_invalid": ["API 密钥无效", "Api_key is invalid"],
  "mail.credentials_need_tls": ["为保护密码，SMTP 账号只能通过 TLS 发送（加密方式选 STARTTLS 或 TLS）", "Credentials are only sent over TLS (security starttls or tls)"],
  "mail.enable_needs_api_key": ["启用发信前请填写 API 密钥与发件地址", "An API key and from_addr are required to enable sending"],
  "mail.enable_needs_host": ["启用发信前请填写 SMTP 服务器与发件地址", "Host and from_addr are required to enable sending"],
  "mail.expiry_days_range": ["到期提醒天数须为 0–30", "Notify_expiry_days must be 0-30"],
  "mail.from_invalid": ["发件地址不是有效的邮箱地址", "From_addr is not a valid email address"],
  "mail.from_name_long": ["发件人名称最多 64 个字符", "From_name must be at most 64 characters"],
  "mail.host_invalid": ["SMTP 服务器须为主机名或 IP 地址", "Host must be a host name or IP address"],
  "mail.password_invalid": ["SMTP 密码无效", "Password is invalid"],
  "mail.provider_invalid": ["不支持的发信方式", "Unknown mail provider"],
  "mail.retry_not_dead": ["只能重试尚未过期的失败邮件", "Only a dead letter that has not expired can be retried"],
  "mail.security_invalid": ["加密方式只能是 STARTTLS、TLS 或无", "Security must be starttls, tls or none"],
  "mail.status_invalid": ["状态只能是失败、待发送或已发送", "Status must be dead, pending or sent"],
  "mail.test_failed": ["测试邮件发送失败：{detail}", "{detail}"],
  "mail.test_needs_host": ["请先保存 SMTP 服务器和发件地址", "Save the SMTP host and sender address first"],
  "mail.to_invalid": ["收件地址不是有效的邮箱地址", "To is not a valid email address"],
  "mail.username_invalid": ["SMTP 用户名无效", "Username is invalid"],
  "mail_template.body_control": ["正文不能含控制字符", "Body must not contain control characters"],
  "mail_template.body_length": ["正文须为 1–{max} 个字符", "Body must be 1-{max} characters"],
  "mail_template.kind_unknown": ["未知的邮件种类：{kind}", "Unknown template kind: {kind}"],
  "mail_template.locale_invalid": ["语言只能是中文或英文", "Locale must be zh or en"],
  "mail_template.placeholder_missing": ["模板必须包含占位符 {name}", "The template must contain {{name}}"],
  "mail_template.placeholder_unknown": ["未知占位符 {name}（只能使用列出的占位符）", "Unknown placeholder {{name}}"],
  "mail_template.subject_length": ["主题须为 1–{max} 个字符", "Subject must be 1-{max} characters"],
  "mail_template.subject_multiline": ["主题只能是一行", "Subject must be a single line"],
  "mail_template.version_conflict": ["模板已被修改（可能是其他管理员），请刷新后重试", "The template was changed meanwhile (perhaps by another admin); reload and retry"],
  "node.acme_agent_too_old": ["该服务器的 agent 版本过旧（协议 {p} < {need}），不支持自动证书：请先升级 agent（升级发布，或在服务器上重新运行一次安装命令），或清空服务器域名并手动放置证书", "This server's agent is too old (protocol {p} < {need}) for automatic certificates: upgrade the agent first, or clear the server domain and place the certificate by hand"],
  "node.display_name_invalid": ["显示名称最多 {max_display_chars} 个可打印字符", "Display_name must be at most {max_display_chars} printable characters"],
  "node.max_rate_invalid": ["计费速率上限必须大于 0", "Traffic_max_rate_bytes_per_sec must be > 0"],
  "node.name_empty": ["节点名称不能为空", "Name must not be empty"],
  "node.name_exists": ["已存在同名的节点", "A node with this name exists"],
  "node.name_invalid": ["节点名称须为 1–64 个字符，不能含控制字符", "Name must be 1-64 characters without control characters"],
  "node.probe_cooldown": ["刚刚已经请求过测速，请稍后再试", "A latency test was requested moments ago"],
  "node.range_invalid": ["时间范围只能是 1h、6h、24h、48h、7d、30d、90d", "Range must be one of 1h, 6h, 24h, 48h, 7d, 30d, 90d"],
  "node.region_long": ["地区最多 64 个字符", "Region must be at most 64 characters"],
  "node.server_fields": ["服务器域名与安装链接属于服务器：在服务器上修改", "Tls_domain and install belong to the server (PATCH /servers/{id}, POST /servers/{id}/install)"],
  "node.sort_range": ["排序值须在 -{sort_limit} 到 {sort_limit} 之间", "Sort must be between -{sort_limit} and {sort_limit}"],
  "node.tag_invalid": ["每个标签最多 {max_tag_chars} 个可打印字符，且不能含「|」", "Each tag must be at most {max_tag_chars} printable characters without '|'"],
  "node.template_and_inbound": ["模板与入站 JSON 只能二选一", "Give either template or inbound, not both"],
  "node.tls_domain_invalid": ["节点域名须为形如 node1.example.com 的域名（不能是 IP 或通配符）", "Tls_domain must be a domain name like node1.example.com (no IP, no wildcard)"],
  "node.too_many_tags": ["标签最多 {max_tags} 个", "At most {max_tags} tags"],
  "node.view_invalid": ["视图参数只能是 summary 或 full", "View must be summary or full"],
  "order.gateway_unavailable": ["支付服务暂时不可用，请稍后重试", "The payment service is unavailable. Please try again."],
  "order.in_progress": ["另一个订单正在创建，请稍候", "Another order is being created. Please wait."],
  "order.method_required": ["请选择支付方式", "Choose a payment method."],
  "order.method_unavailable": ["该支付方式暂不可用，请选择其他方式", "This payment method is not available right now; choose another one."],
  "order.not_pending": ["该订单已不是待付款状态", "This order is no longer awaiting payment."],
  "order.payments_off": ["暂不支持在线购买", "Online purchase is not available."],
  "order_admin.already_fulfilled": ["该订单已开通", "Order is already fulfilled"],
  "order_admin.already_refunded": ["该订单已退款", "The order was already refunded"],
  "order_admin.manual_not_fulfilled": ["套餐无法开通，人工订单未创建：{error}", "The plan could not be granted: {error}"],
  "order_admin.no_price": ["该套餐没有这个周期的价格，请先在「套餐」页定价", "The plan has no price for this period"],
  "order_admin.plan_gone": ["套餐已不存在", "The plan no longer exists"],
  "order_admin.refund_external_range": ["支付宝后台退款金额须为 0–{amount_cents} 分（不超过实付金额）", "External_cents must be 0..={amount_cents}"],
  "order_admin.refund_external_required": ["请填写在支付宝商家后台实际退款的金额", "Enter the amount refunded in the payment provider's console (external_cents)"],
  "order_admin.refund_external_with_balance": ["已选择退到余额，不能再填写支付宝后台退款金额", "The gateway amount goes to the balance; do not also record an external refund"],
  "order_admin.refund_gateway_failed": ["支付宝拒绝了退款：{detail}（没有退出任何金额，可以重试或改用其他方式）", "The payment provider refused the refund: {detail}"],
  "order_admin.refund_in_progress": ["该订单有一笔正在进行的原路退款，等支付宝确认后再操作", "A refund through the payment provider is in progress"],
  "order_admin.refund_not_paid": ["只有已付款的订单可以退款", "Only a paid order can be refunded"],
  "order_admin.refund_original_conflict": ["原路退款不能同时选择退到余额或填写后台已退金额", "An original-route refund goes back to the payer: not with to_balance or external_cents"],
  "order_admin.refund_original_range": ["原路退款金额须为 0.01–{amount_yuan} 元", "The original-route refund must be 1..={amount_cents} cents"],
  "order_admin.refund_original_unavailable": ["该订单的支付方式未开启原路退款", "This order's payment method does not allow original-route refunds"],
  "order_admin.refund_user_gone": ["用户已删除：请线下退款，不要选择「退回余额」", "The user no longer exists; refund out of band without to_balance"],
  "order_admin.refunded": ["该订单已退款，不能再开通", "The order was refunded"],
  "order_admin.superseded": ["下单后用户已另购或更换套餐：迟到的付款不替换当前套餐（已自动退回余额）", "The buyer's plan changed after the order was created; not replaced"],
  "order_admin.user_gone": ["用户已不存在", "The user no longer exists"],
  "order_admin.user_has_pending": ["该用户有待付款订单，请先取消或等待其结束", "The user has a pending order; cancel it or wait for it to end"],
  "payments.app_id_invalid": ["APPID 须为 1–32 位数字", "App_id must be 1-32 digits"],
  "payments.config_invalid": ["配置格式错误", "Config must be an object"],
  "payments.config_unknown_field": ["未知的配置项：{field}", "Unknown config field: {field}"],
  "payments.environment_invalid": ["环境须为 沙箱 / 正式 / 自定义网关", "Environment must be sandbox, production or custom"],
  "payments.gateway_invalid": ["自定义网关须为 https 地址（http 仅限本机回环）", "Custom gateway must be an https URL (http only on loopback)"],
  "payments.gateway_unexpected": ["只有「自定义网关」环境才能填写网关地址", "Gateway_url is only for the custom environment"],
  "payments.icon_invalid": ["图标须为 1–32 个小写字母、数字、- 或 _", "Icon must be 1-32 of a-z 0-9 - _"],
  "payments.incomplete": ["配置不完整：启用前请填写 APPID、应用私钥与支付宝公钥", "Enabling needs the app_id, the app private key and the Alipay public key"],
  "payments.kind_immutable": ["支付方式的类型不能修改，请新增一个", "The kind of a method cannot change; add a new method"],
  "payments.kind_unknown": ["未知的支付方式类型：{kind}", "Unknown payment method kind: {kind}"],
  "payments.method_in_use": ["已有订单使用该支付方式，不能删除（可以停用）", "Orders use this payment method; disable it instead"],
  "payments.name_invalid": ["名称须为 1–64 个字符，不能含控制字符", "Display_name must be 1-64 characters without control characters"],
  "payments.not_configured": ["请先保存完整的配置再测试连接", "Save a complete configuration first"],
  "payments.private_key_invalid": ["应用私钥无效：请粘贴 RSA 私钥（PEM 或支付宝密钥工具生成的 base64）", "App private key: not an RSA private key in PEM or base64"],
  "payments.private_key_too_short": ["应用私钥太短：RSA2 需要至少 2048 位", "App private key: RSA2 needs at least 2048 bits"],
  "payments.public_key_invalid": ["支付宝公钥无效：请粘贴 RSA 公钥（PEM 或 base64）", "Alipay public key: not an RSA public key in PEM or base64"],
  "payments.public_key_is_app_key": ["填写的是应用公钥，不是支付宝公钥：请在支付宝开放平台复制「支付宝公钥」", "The Alipay public key is the app's own public key; paste the Alipay public key"],
  "payments.public_key_is_private": ["支付宝公钥一栏填入的是私钥：请改填支付宝公钥（不要外泄私钥）", "Alipay public key: this is a private key"],
  "payments.public_key_too_short": ["支付宝公钥太短：RSA2 需要至少 2048 位", "Alipay public key: RSA2 needs at least 2048 bits"],
  "payments.refund_original_invalid": ["「允许原路退款」只能是开或关", "Refund_original must be true or false"],
  "payments.seller_id_invalid": ["商户 PID 须为数字（2088 开头）", "Seller_id must be 1-32 digits (2088...)"],
  "payments.sort_range": ["排序值须在 ±1000000 之内", "Sort must be within ±1000000"],
  "payments.stored_key_unreadable": ["已保存的密钥无法解密（data/master.key 已更换？）：请重新粘贴", "The stored app private key cannot be opened (data/master.key changed); paste it again"],
  "payments.timeout_range": ["订单有效期须为 5–120 分钟", "Order_timeout_minutes must be 5-120"],
  "plan.capacity_negative": ["库存不能为负数", "Capacity must be >= 0"],
  "plan.description_control": ["说明不能包含控制字符", "Description must not contain control characters"],
  "plan.description_long": ["说明最多 {max_plan_description} 个字符", "Description must be at most {max_plan_description} characters"],
  "plan.disabled": ["该套餐已停用，不能分配", "Plan is disabled (not offered)"],
  "plan.in_use": ["有 {active} 个用户正在使用此套餐：请先为他们更换或取消套餐（或改为停用此套餐）", "{active} user(s) hold this plan; change or cancel their plans first (or disable the plan to stop offering it)"],
  "plan.name_exists": ["已存在同名的套餐", "Plan name already exists"],
  "plan.name_length": ["名称须为 1–{max_name} 个字符", "{field} must be 1-{max_name} characters"],
  "plan.on_sale_needs_price": ["上架的套餐至少需要一个流量重置包以外的价格", "A plan on sale needs at least one price other than the reset pack"],
  "plan.period_invalid": ["流量重置周期无效（每月 / 不重置 / 每 1–{max_period_days} 天）", "Period must be \"monthly\", \"none\" or \"days-N\" (N = 1..{max_period_days})"],
  "plan.price_days_missing": ["「自定义天数」需要填写天数", "Period \"days\" needs days"],
  "plan.price_days_range": ["天数须为 1–{max_period_days}", "Days must be 1..={max_period_days}"],
  "plan.price_days_unexpected": ["该周期（{period}）不需要填写天数", "Period {period} takes no days"],
  "plan.price_duplicate": ["同一周期（{period}）只能有一个价格", "Duplicate price for period {period}"],
  "plan.price_range": ["价格须在 0.01–{max_price_yuan} 元之间", "Price_cents must be 1..={max_price_cents} (integer cents)"],
  "plan.quota_negative": ["流量额度不能为负数", "Traffic_quota_bytes must be >= 0"],
  "plan.seats_negative": ["设备数不能为负数", "Device_seats must be >= 0"],
  "plan.speed_limit_range": ["限速须为 1–{max_speed_mbps} Mbps", "Speed_limit_mbps must be 1..={max}"],
  "plan.unknown": ["套餐不存在（可能已被删除）", "Unknown plan id"],
  "plan.unknown_ref": ["选择的{what}不存在（可能已被删除）", "Unknown {what} id"],
  "release.binary_exists": ["该发布的程序文件已上传", "Binary already uploaded"],
  "release.binary_mismatch": ["程序文件与签名清单不符（{total} 字节，sha256 {sha}）", "Binary does not match the signed manifest (got {total} bytes, sha256 {sha})"],
  "release.binary_too_large": ["程序文件超过清单声明的 {size} 字节", "Binary larger than the manifest's {size} bytes"],
  "release.exists": ["相同版本/平台或相同摘要的发布已存在", "A release with this version/platform or digest already exists"],
  "release.manifest_invalid": ["发布清单无效：{detail}", "{detail}"],
  "release.no_keys": ["面板没有可用的发布公钥（系统设置 → 安全），自动更新已关闭", "No release keys are trusted (Settings → Security): self-update is off"],
  "release.panel_too_old": ["该版本需要面板协议 {needed}（当前面板为 {have}），请先升级面板", "Release needs panel protocol {needed} (this panel speaks {have}): upgrade the panel first"],
  "release.rollout_open": ["有未结束的灰度更新使用此版本，请先中止", "An open rollout targets this version: abort it first"],
  "release.signature_invalid": ["签名校验失败：{detail}", "{detail}"],
  "release.upload_interrupted": ["上传中断，请重试", "Upload interrupted"],
  "request.body_too_large": ["提交的内容过大", "The request is too large"],
  "request.field_not_null": ["{field} 不能为空", "{field} cannot be empty"],
  "request.field_required": ["请填写 {field}", "{field} is required"],
  "request.field_too_long": ["{field} 最多 {max} 个字符", "{field} can be at most {max} characters"],
  "request.internal": ["服务器出错了，请稍后再试", "Something went wrong on the server. Please try again later."],
  "request.invalid_body": ["请求格式不正确：{detail}", "Malformed request: {detail}"],
  "request.no_fields": ["没有任何改动", "Nothing changed"],
  "request.not_found": ["内容不存在或已被删除", "Not found (it may have been deleted)"],
  "request.port_range": ["端口须为 1–65535", "The port must be 1–65535"],
  "request.rate_limited": ["尝试次数过多，请稍后再试", "Too many attempts. Please try again later."],
  "request.reason_length": ["原因须为 1–{max_reason} 个字符", "The reason must be 1–{max_reason} characters"],
  "request.status_invalid": ["状态无效", "Invalid status"],
  "request.traffic_query_invalid": ["查询参数无效：{detail}", "Invalid query: {detail}"],
  "rollout.another_open": ["已有一个未结束的灰度更新，请先完成或中止它", "Another rollout is open: finish or abort it first"],
  "rollout.bad_node": ["所选节点中有不存在、未注册或正在删除的节点", "Server_ids: unknown, unenrolled or deleting server"],
  "rollout.bad_transition": ["当前状态（{status}）不能执行此操作", "Cannot {action} a {status} rollout"],
  "rollout.failure_ratio_range": ["失败比例须在 0–1 之间", "Max_failure_ratio: 0..=1"],
  "rollout.no_nodes": ["没有可更新的已注册节点", "No enrolled server to update"],
  "rollout.no_release": ["还没有上传该版本（先上传清单、签名与程序文件）", "No uploaded release with this version (POST /agent-releases, then PUT its binary)"],
  "rollout.percentage_range": ["百分比须为 1–100", "Percentage: 1..=100"],
  "rollout.timeout_range": ["健康检查超时须为 30–86400 秒", "Health_timeout_secs: 30..=86400"],
  "rollout.version_invalid": ["版本号格式应为 vMAJOR.MINOR.PATCH[-pre]", "Version: vMAJOR.MINOR.PATCH[-pre]"],
  "rollout.waves_invalid": ["分批设置无效：{detail}", "{detail}"],
  "server.deleting": ["服务器正在删除，不能修改", "Server is being deleted"],
  "server.name_exists": ["已存在同名的服务器", "A server with this name exists"],
  "server.name_invalid": ["服务器名称须为 1–64 个字符，不能含控制字符", "Name must be 1-64 characters without control characters"],
  "server.quota_invalid": ["流量额度须大于 0（留空 = 不限）", "Traffic_quota_bytes must be > 0 (null = no quota)"],
  "server.quota_mode_invalid": ["计费方式须为 双向 / 仅上行 / 仅下行", "Traffic_quota_mode must be both, up or down"],
  "server.reset_day_invalid": ["重置日须为 1–31（留空 = 不重置）", "Traffic_quota_reset_day must be 1-31 (null = never)"],
  "settings.acme_email_invalid": ["ACME 邮箱：不是有效的邮箱地址（可留空）", "ACME email: not a valid address (may be empty)"],
  "settings.acme_url_invalid": ["ACME 目录：必须是 https:// 地址（留空 = Let's Encrypt）", "ACME directory: must be an https:// URL (empty = Let's Encrypt)"],
  "settings.allowlist_excludes_you": ["名单里没有你当前的地址 {ip}：保存后你会立即无法访问后台", "The list does not contain your address {ip}"],
  "settings.allowlist_invalid": ["{value} 不是有效的 IP 地址或 CIDR 网段", "{value} is not an address or CIDR block"],
  "settings.allowlist_too_long": ["白名单最多 {max} 条", "At most {max} entries"],
  "settings.audit_retention_invalid": ["审计日志保留天数：0（永久）到 36500", "Audit log retention: 0 (forever) to 36500 days"],
  "settings.cloudflare_range_invalid": ["Cloudflare 网段：{range} 不是有效的 CIDR", "Cloudflare ranges: {range} is not a valid CIDR"],
  "settings.cloudflare_ranges_too_many": ["Cloudflare 网段：最多 {max} 条", "Cloudflare ranges: at most {max}"],
  "settings.confirm_required": ["需要确认后才能执行", "This change takes effect at once: send confirm=true"],
  "settings.domain_conflict": ["{domain} 不能同时是{a}和{b}（一个域名只能有一种用途）", "{domain} cannot be both {a} and {b} (one role per domain)"],
  "settings.domain_duplicate": ["{kind}：{domain} 重复", "{kind}: {domain} is listed twice"],
  "settings.domain_invalid": ["{field}：{e}", "{field}：{e}"],
  "settings.domain_removal_unconfirmed": ["删除域名 {domains} 前需要先确认影响", "Removing {domains} affects places that use it: review the impact and confirm"],
  "settings.domains_too_many": ["{kind}最多 {max} 个", "{kind}: at most {max}"],
  "settings.fallback_url_invalid": ["备用下载地址：必须是含 {arch} 的 https:// 地址，不能有引号、空格或 shell 特殊字符", "Fallback download URL: an https:// URL containing {arch}, without quotes, spaces or shell characters"],
  "settings.host_gate": ["保存后面板只接受主域名/订阅域名（以及 IP 地址）的访问，当前访问地址 {host} 将被拒绝。请确认主域名已解析并能打开，再勾选确认后保存。", "After saving, the console answers on the main domain (and IP addresses) only; the current address {host} will be refused. Make sure the main domain resolves and opens, then confirm."],
  "settings.node_domain_cloudflare": ["{detail}", "{detail}"],
  "settings.node_domain_unset": ["节点通信域名未设置：请先在「系统设置 → 节点通信」填写节点连接面板所用的域名或 IP", "The node communication domain is not set: set the domain or IP the agents use to reach the panel first (Settings → Domains)"],
  "settings.node_domain_unspecified": ["节点通信域名：不能是 0.0.0.0 / ::", "Node communication domain: cannot be 0.0.0.0 / ::"],
  "settings.path_invalid": ["只能使用 {min}–64 个字母、数字、- 或 _", "Use {min}-64 characters of A-Z a-z 0-9 - _"],
  "settings.path_reserved": ["{value} 已被门户使用，请换一个", "{value} is used by the portal"],
  "settings.path_taken": ["这个值已被后台前缀或订阅路径使用", "That value is already in use"],
  "settings.probe_interval_range": ["测速间隔：须在 600 秒（10 分钟）到 604800 秒（7 天）之间", "Probe interval: between 600 seconds (10 minutes) and 604800 seconds (7 days)"],
  "settings.probe_url_duplicate": ["测速地址：不能重复", "Probe URLs: no duplicates"],
  "settings.probe_url_invalid": ["测速地址：{bad} 不是有效的 http(s) 地址（不能含空白或用户名）", "Probe URLs: {bad} is not a valid http(s) URL (no whitespace or user name)"],
  "settings.probe_urls_too_many": ["测速地址：最多 4 个", "Probe URLs: at most 4"],
  "settings.release_key_invalid": ["额外信任的发布公钥：{detail}（每行一个「base64 公钥 标签」）", "Extra release keys: {detail} (one \"<base64 key> [label]\" per line)"],
  "settings.release_keys_too_many": ["额外信任的发布公钥：最多 {max} 个", "Extra release keys: at most {max}"],
  "settings.server_name_locked": ["{detail}", "{detail}"],
  "settings.site_name_invalid": ["站点名称须为 1–{max} 个字符，不能含控制字符", "Site name must be 1-{max} characters without control characters"],
  "settings.sub_format_invalid": ["未知的订阅格式：{value}（clash、sing-box、links）", "Unknown subscription format {value} (clash, sing-box, links)"],
  "settings.sub_import_client_invalid": ["未知的导入客户端：{value}（clash、stash、shadowrocket、sing-box、hiddify）", "Unknown import client {value} (clash, stash, shadowrocket, sing-box, hiddify)"],
  "settings.sub_rule_invalid": ["分流规则无效：第 {index} 条（{detail}）", "Rule {index}: {detail}"],
  "settings.sub_rule_set_url_invalid": ["规则列表地址须为 https，并包含 {name}（可选 {kind}）", "The rule list URL must be https and contain {name} (and optionally {kind})"],
  "settings.sub_rules_too_many": ["分流规则最多 {max} 条", "At most {max} routing rules"],
  "settings.timezone_invalid": ["未知的时区「{tz}」（请填写 IANA 名称，如 Asia/Shanghai）", "Unknown time zone {tz} (an IANA name such as Asia/Shanghai)"],
  "settings.tls_pin_invalid": ["安装命令公钥钉扎：格式应为 sha256//<base64>（留空 = 自动探测）", "Install TLS pin: sha256//<base64 SHA-256 of the SPKI> (empty = probe automatically)"],
  "settings.traffic_retention_invalid": ["流量明细保留天数：0（永久）或 32 到 36500", "Traffic history retention: 0 (forever) or 32 to 36500 days"],
  "settings.version_conflict": ["设置已被修改（可能是其他管理员），请刷新后重试", "The settings were changed meanwhile (perhaps by another admin); reload and retry"],
  "shop.admin_cannot_buy": ["管理员账户不能购买套餐", "Admin accounts cannot buy plans"],
  "shop.no_switch": ["不支持从当前套餐更换到该套餐", "You cannot switch to this plan from your current plan."],
  "shop.not_for_sale": ["该套餐当前不可购买", "This plan is not for sale right now."],
  "shop.nothing_to_renew": ["当前套餐长期有效，无需续费", "Your current plan does not expire; there is nothing to renew."],
  "shop.renewal_only": ["该套餐仅限现有用户续费", "This plan can only be renewed by its current subscribers."],
  "shop.reset_needs_plan": ["流量重置包仅限当前使用该套餐的用户购买", "Traffic reset packs are only for current subscribers of this plan."],
  "shop.sold_out": ["该套餐已售罄", "This plan is sold out."],
  "signup.challenge_invalid": ["人机校验失败或已过期，请重试", "The anti-bot check failed or expired; please try again."],
  "signup.domain_not_allowed": ["不支持该邮箱域名", "This email domain is not accepted."],
  "signup.invalid_code": ["验证码错误或已过期，请重新获取", "Wrong or expired code. Request a new one."],
  "signup.invalid_email": ["邮箱地址格式不正确", "Enter a valid email address."],
  "signup.invalid_invite": ["邀请码无效或已被使用", "The invite code is invalid or has been used."],
  "signup.invalid_link": ["链接无效或已过期，请重新申请重置", "This link is invalid or has expired. Request a new reset."],
  "signup.invite_required": ["注册需要邀请码", "An invite code is required to sign up."],
  "signup.unavailable": ["该邮箱无法注册。如果这是你的邮箱，请直接登录或找回密码", "This email address cannot be registered. If it is yours, log in or reset your password."],
  "signup_admin.domain_invalid": ["邮箱域名无效：{d}", "Invalid email domain: {d}"],
  "signup_admin.invites_range": ["每人邀请码数量须为 0–100", "Invite_codes_per_user must be 0-100"],
  "signup_admin.mail_off": ["请先在「系统设置 → 邮件」启用发信", "Enable mail sending first (Settings → Mail)"],
  "signup_admin.needs_main_domain": ["请先设置主域名：找回密码链接需要它", "Set the main domain first: reset links need it"],
  "signup_admin.too_many_domains": ["邮箱域名最多 100 个", "At most 100 email domains"],
  "signup_admin.trial_days_range": ["试用天数须为 1–3650", "Trial_days must be 1-3650"],
  "signup_admin.unknown_trial_plan": ["试用套餐不存在", "Unknown trial plan"],
  "template.dest_invalid": ["目标站点须为域名（可带 :端口）", "Dest must be a domain name (optionally :port)"],
  "template.dest_port": ["目标端口须为 1–65535", "Dest port must be 1-65535"],
  "template.domain_invalid": ["{what} 须为节点证书的域名", "{what} must be the domain name of the node's certificate"],
  "template.domain_mismatch": ["{what} {d} 与节点域名 {n} 不同：自动证书只覆盖 {n}（留空即使用节点域名）", "{what} {d} differs from the node's TLS domain {n}: the automatic certificate covers only {n} (leave {what} empty to use it)"],
  "template.domain_missing": ["{what}：请设置节点域名，或为此入站填写域名", "{what}: set the server's TLS domain or a domain for this inbound"],
  "template.fingerprint_invalid": ["指纹只能是：{allowed}", "Fingerprint must be one of {allowed}"],
  "template.method_invalid": ["加密方式只能是：{allowed}", "Method must be one of {allowed}"],
  "template.mode_invalid": ["XHTTP 模式只能是：{allowed}", "Mode must be one of {allowed}"],
  "template.needs_tls": ["Trojan 与 gRPC 需要 TLS（开启 TLS 并设置节点域名，或填写证书域名）", "Trojan and grpc need TLS (tls: true with the node's TLS domain, or tls_domain)"],
  "template.network_invalid": ["传输方式只能是 WebSocket、HTTPUpgrade、XHTTP 或 gRPC", "Network must be ws, httpupgrade, xhttp or grpc"],
  "template.path_invalid": ["路径须以 / 开头，只含字母、数字和 /-_.~（不超过 128 个字符）", "Path must start with / and use only letters, digits and /-_.~ (<= 128)"],
  "template.port_clash": ["端口 {p} 已被其他入站占用", "Port {p} is used by more than one inbound"],
  "template.protocol_invalid": ["协议只能是 VLESS、VMess 或 Trojan", "Protocol must be vless, vmess or trojan"],
  "template.service_name_invalid": ["gRPC 服务名只能含字母、数字和 -_.（不超过 64 个字符）", "Service_name: letters, digits and -_. only (<= 64)"],
  "template.tls_domain_without_tls": ["未开启 TLS 却填写了证书域名", "Tls is false but tls_domain is set"],
  "ticket.choice_invalid": ["{field} 只能是：{allowed}", "{field} must be one of: {allowed}"],
  "ticket.closed": ["工单已关闭", "The ticket is closed"],
  "ticket.full": ["这个工单的消息已达上限，请新建工单", "This ticket has reached its message limit; open a new one"],
  "ticket.message_long": ["内容最多 {max_body} 个字符", "The message can be at most {max_body} characters"],
  "ticket.message_required": ["请填写内容", "Enter a message"],
  "ticket.open_limit": ["未关闭的工单过多，请先关闭已解决的工单", "Too many open tickets; close the solved ones first"],
  "ticket.subject_long": ["标题最多 {max_subject} 个字符", "The subject can be at most {max_subject} characters"],
  "ticket.subject_multiline": ["标题只能是一行", "The subject must be a single line"],
  "ticket.subject_required": ["请填写标题", "Enter a subject"],
  "ticket.unknown_node": ["所选节点不存在", "The selected node does not exist"],
  "ticket.unknown_order": ["所选订单不存在", "The selected order does not exist"],
  "ticket_admin.assignee_filter": ["负责人筛选只能是「我」「未分配」或某个管理员", "Assignee must be me, none or an id"],
  "ticket_admin.assignee_invalid": ["负责人必须是已启用的管理员", "Assignee must be an enabled admin"],
  "ticket_admin.not_closed": ["工单未关闭", "Ticket is not closed"],
  "ticket_admin.search_long": ["搜索内容最多 64 个字符", "Search text is longer than 64 characters"],
  "ticket_admin.status_invalid": ["状态筛选无效", "Status must be open, answered, closed or active"],
  "user.admin_no_plan": ["管理员账户不是代理用户，不能分配套餐", "Admin accounts are not proxy users and cannot have a plan"],
  "user.admin_no_subscription": ["管理员账户没有订阅链接", "Admin accounts have no subscription"],
  "user.ban_reason_required": ["请填写封禁原因（会显示给用户）", "A ban needs a reason (it is shown to the user)"],
  "user.ban_reason_too_long": ["封禁原因最多 {max} 个字符", "The reason is longer than {max} characters"],
  "user.ban_self": ["不能封禁自己的账户", "You cannot ban your own account"],
  "user.bulk_delete_changed": ["删除范围已变化：请重新预览数量后再确认", "The selection changed since the preview: preview again"],
  "user.bulk_delete_too_many": ["一次最多删除 {max} 个账号：请缩小范围", "At most {max} accounts at once: narrow the selection"],
  "user.date_filter_invalid": ["{field}：日期格式应为 YYYY-MM-DD", "{field} must be a day YYYY-MM-DD"],
  "user.delete_confirm_required": ["删除用户前需要先确认影响（余额、提现、订单、套餐）", "Deleting a user needs confirm=true (see GET /users/{id}/delete-impact)"],
  "user.email_exists": ["已有其他账户使用这个邮箱", "Another account already uses this email address"],
  "user.erase_admin": ["管理员账号不能注销：请先降级", "Admin accounts are not erased: demote the account first"],
  "user.erased": ["该账号已注销（匿名化保留），不能再修改", "The account was deleted"],
  "user.has_plan": ["该用户有生效中的套餐：请先取消套餐，再设为管理员", "The user has an active plan; cancel it before making the account an admin"],
  "user.not_banned": ["该账户没有被封禁", "The account is not banned"],
  "user.owner_already": ["该账号已经是所有者", "This account is already the owner"],
  "user.owner_confirm_required": ["转让所有者需要二次确认", "Transferring the ownership needs confirm=true"],
  "user.owner_only": ["只有所有者可以执行此操作（管理其他管理员、后台前缀与白名单、支付渠道密钥）", "Only the owner may do this (admin accounts, admin prefix, payment keys)"],
  "user.owner_protected": ["所有者不能被降级、封禁或删除：请先把所有者转让给另一位管理员", "The owner cannot be demoted, banned or deleted; transfer the ownership first"],
  "user.owner_target": ["只能转让给已启用的管理员", "Only an enabled admin can become the owner"],
  "user.plan_filter_invalid": ["套餐筛选无效", "Plan_id must be a plan id or none"],
  "user.promote_banned": ["该账号已被封禁：请先解封，再设为管理员", "The account is banned; unban it before making it an admin"],
  "user.query_too_long": ["搜索内容最多 {max} 个字符", "Q is longer than {max} characters"],
  "user.role_invalid": ["角色只能是用户或管理员", "Role must be 'user' or 'admin'"],
  "user.sort_invalid": ["排序方式无效", "Sort must be created, -created, email, -traffic or expires"],
  "user.status_filter_invalid": ["状态筛选无效", "Status must be active, expired, quota, banned or erased"],
  "user_plan.confirm_required": ["重置流量需要确认", "Resetting the traffic needs confirm: true"],
  "user_plan.extend_days_range": ["延长天数须为 1–{max_period_days}", "Extend_days must be 1..={max_period_days}"],
  "user_plan.extend_onetime": ["一次性套餐不能按天延长：请续期一个时长或重新分配套餐", "A one-time purchase cannot be extended by days; renew it or assign a plan"],
  "user_plan.no_expiry": ["该订阅没有到期时间，无需续期", "The subscription has no expiry; nothing to renew"],
  "user_plan.none": ["该用户没有生效的套餐", "The user has no active plan"],
  "user_plan.renew_mode": ["续期请选择「续期一个时长」或「延长 N 天」之一", "Send either period (with days when needed) or extend_days"],
  "user_plan.term_days_missing": ["「自定义天数」需要填写天数", "Period \"days\" needs days"],
  "user_plan.term_days_range": ["天数须为 1–{max_period_days}", "Days must be 1..={max_period_days}"],
  "user_plan.term_days_unexpected": ["该时长不需要天数", "Period {period} takes no days"],
  "user_plan.term_reset": ["流量重置包不是套餐时长", "The traffic reset pack is not a subscription term"],
  "withdrawal.address_invalid": ["这不是有效的 {chain} 地址，请核对网络与地址", "This is not a valid {chain} address. Check the network and the address."],
  "withdrawal.amount_range": ["提现金额须在 0.01–{max_price_yuan} 元之间", "The amount must be ¥0.01–¥{max_price_yuan}"],
  "withdrawal.below_minimum": ["最低提现金额为 {min_yuan} 元", "The minimum withdrawal is ¥{min_yuan}"],
  "withdrawal.chain_invalid": ["该网络暂不支持提现", "This network is not available for withdrawals."],
  "withdrawal.exceeds": ["提现金额超过可提现余额", "The amount exceeds your withdrawable balance."],
  "withdrawal.memo_invalid": ["Memo 须为 1–{max} 个字符", "The memo must be 1–{max} characters."],
  "withdrawal.memo_unexpected": ["只有 TON 提现可以填写 Memo", "Only TON withdrawals take a memo."],
  "withdrawal.not_pending": ["该提现申请已处理", "This withdrawal request has already been handled."],
  "withdrawal.open": ["你已有一笔待处理的提现申请", "You already have an open withdrawal request."],
  "withdrawal.txid_invalid": ["请填写交易哈希", "Enter the transaction hash."],
  "withdrawal.usdt_amount_invalid": ["请填写大于 0、最多 6 位小数的 USDT 数量", "Enter a positive USDT amount with at most 6 decimals."],
};
