#!/usr/bin/env python3
"""Independent reference implementation of the state hash (agent.proto,
"State hash"). Regenerates ../state_hash_vectors.json; both repos' tests
check their own implementation against that file. Run from this directory:
    python3 gen_vectors.py
then copy state_hash_vectors.json to akari-agent/proto/."""
import hashlib, json, os, struct

def state_hash(config_version, inbounds_json, users):
    recs = {}
    for u in users:
        for iu in u["inbound_users"]:  # later entry for a tag wins
            recs[(u["user_id"].encode(), iu["inbound_tag"].encode())] = (iu["protocol"], iu["account_json"])
    m = hashlib.sha256()
    m.update(b"akari-state-v2\n")
    m.update(struct.pack(">Q", config_version))
    for (uid, tag) in sorted(recs):
        proto, acct = recs[(uid, tag)]
        for f in (uid, tag, proto.encode(), acct.encode()):
            m.update(struct.pack(">I", len(f)))
            m.update(f)
    inb = hashlib.sha256(inbounds_json.encode()).digest()
    m.update(struct.pack(">I", len(inb)))
    m.update(inb)
    return m.hexdigest()

A = "11111111-1111-1111-1111-111111111111"
B = "22222222-2222-2222-2222-222222222222"
C = "0aaaaaaa-0000-0000-0000-000000000000"
INB = '[{"port":443,"protocol":"vless","settings":{"clients":[],"decryption":"none"},"tag":"in-vless"}]'
def iu(t, p, a): return {"inbound_tag": t, "protocol": p, "account_json": a}

cases = [
    {"name": "empty, nothing running", "config_version": 0, "inbounds_json": "", "users": []},
    {"name": "empty user set", "config_version": 1, "inbounds_json": INB, "users": []},
    {"name": "one user one inbound", "config_version": 3, "inbounds_json": INB,
     "users": [{"user_id": A, "inbound_users": [iu("in-vless", "vless", '{"flow":"","id":"9d3c6f55-1b1e-4c55-8a4b-000000000001"}')]}]},
    {"name": "input order does not matter", "config_version": 3, "inbounds_json": INB, "users": [
        {"user_id": B, "inbound_users": [iu("in-vmess", "vmess", '{"id":"b-vmess"}'), iu("in-trojan", "trojan", '{"password":"p"}')]},
        {"user_id": A, "inbound_users": [iu("in-vless", "vless", '{"flow":"","id":"a"}')]},
        {"user_id": C, "inbound_users": [iu("in-vless", "vless", '{"flow":"xtls-rprx-vision","id":"c"}')]}]},
    {"name": "later inbound for the same tag replaces the earlier one", "config_version": 3, "inbounds_json": INB,
     "users": [{"user_id": A, "inbound_users": [iu("in-vless", "vless", '{"flow":"","id":"old"}'), iu("in-vless", "vless", '{"flow":"","id":"new"}')]}]},
    {"name": "user without inbounds contributes nothing", "config_version": 3, "inbounds_json": INB,
     "users": [{"user_id": B, "inbound_users": []}, {"user_id": A, "inbound_users": [iu("in-vless", "vless", '{"flow":"","id":"new"}')]}]},
    {"name": "config version is bound (u64 big-endian)", "config_version": 9223372036854775813, "inbounds_json": INB,
     "users": [{"user_id": A, "inbound_users": [iu("in-vless", "vless", '{"flow":"","id":"new"}')]}]},
    {"name": "account json is hashed verbatim", "config_version": 3, "inbounds_json": INB,
     "users": [{"user_id": A, "inbound_users": [iu("in-vless", "vless", '{"id":"new","flow":""}')]}]},
    {"name": "inbounds are bound (same users, other inbounds)", "config_version": 3,
     "inbounds_json": INB.replace("443", "8443"),
     "users": [{"user_id": A, "inbound_users": [iu("in-vless", "vless", '{"flow":"","id":"new"}')]}]},
    {"name": "non-ASCII and JSON escapes are hashed as the decoded UTF-8 string", "config_version": 7,
     "inbounds_json": '[{"protocol":"trojan","tag":"入口-ü","settings":{"note":"a\\"b\\\\c\\u00e9\\n"}}]',
     "users": [{"user_id": A, "inbound_users": [
         iu("入口-ü", "trojan", '{"password":"pässwörd 日本語 🔑"}'),
         iu("t-esc", "trojan", '{"password":"q\\"uote\\\\back\\u0000nul\\u2028ls\\ttab"}')]}]},
    {"name": "control characters and U+2028/2029 raw in account json", "config_version": 8, "inbounds_json": INB,
     "users": [{"user_id": B, "inbound_users": [iu("in-vless", "vless", '{"id":"x  \u0001\u007f"}')]}]},
]
for c in cases:
    c["hash"] = state_hash(c["config_version"], c["inbounds_json"], c["users"])
assert cases[4]["hash"] == cases[5]["hash"]
assert len({c["hash"] for c in cases}) == len(cases) - 1

out = {"_comment": "Generated by proto/testdata/gen_vectors.py (independent reference). Canonical copy in akari-panel/proto/; akari-agent vendors it next to agent.proto. Both repos' tests must pass against it.",
       "cases": cases}
here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "..", "state_hash_vectors.json"), "w", encoding="utf-8") as f:
    f.write(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
