#!/usr/bin/env python3
"""W29: refresh the vendored built-in block lists (src/blockrules/lists/).

Source: v2fly/domain-list-community (MIT, https://github.com/v2fly/domain-list-community).
Each built-in rule set is a union of upstream data files; `include:` lines
are resolved, attributes (`@cn`, `@!cn`, ...) dropped, `regexp:` entries
refused (the panel only ships suffix/full/keyword matchers: linear-time,
compiled by xray into its succinct domain matcher). The output is
deterministic (sorted, deduplicated) and records the upstream commit, so a
refresh is one reviewable diff:

    scripts/update-block-lists.py            # latest upstream master
    scripts/update-block-lists.py <commit>   # a pinned commit

Needs git and network access; writes nothing on failure.
"""

import os
import re
import subprocess
import sys
import tempfile

REPO = "https://github.com/v2fly/domain-list-community"
SETS = {
    "bt_tracker": ["category-public-tracker"],
    "xunlei_pt": ["xunlei", "category-pt"],
}
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "blockrules", "lists")
LABEL = re.compile(r"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")
KEYWORD = re.compile(r"^[a-z0-9.-]{1,64}$")


def entries(data_dir, name, seen):
    if name in seen:
        return []
    seen.add(name)
    out = []
    with open(os.path.join(data_dir, name), encoding="utf-8") as f:
        for raw in f:
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            line = line.split("@", 1)[0].strip()
            if line.startswith("include:"):
                out += entries(data_dir, line[len("include:"):].strip(), seen)
                continue
            kind, _, value = line.partition(":") if ":" in line else ("domain", ":", line)
            value = value.strip().lower()
            if kind == "regexp":
                sys.exit(f"{name}: regexp entries are not supported: {value}")
            if kind in ("domain", "full"):
                if len(value) > 253 or not LABEL.match(value):
                    sys.exit(f"{name}: bad domain {value!r}")
            elif kind == "keyword":
                if not KEYWORD.match(value):
                    sys.exit(f"{name}: bad keyword {value!r}")
            else:
                sys.exit(f"{name}: unknown entry kind {kind!r}")
            out.append(f"{kind}:{value}")
    return out


def main():
    rev = sys.argv[1] if len(sys.argv) > 1 else "master"
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(["git", "clone", "-q", "--filter=blob:none", REPO, tmp], check=True)
        subprocess.run(["git", "-C", tmp, "checkout", "-q", rev], check=True)
        commit = subprocess.run(
            ["git", "-C", tmp, "rev-parse", "HEAD"], check=True, capture_output=True, text=True
        ).stdout.strip()
        date = subprocess.run(
            ["git", "-C", tmp, "show", "-s", "--format=%cs", "HEAD"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
        data = os.path.join(tmp, "data")
        rendered = {}
        for key, files in SETS.items():
            seen = set()
            items = sorted({e for f in files for e in entries(data, f, seen)})
            if not items:
                sys.exit(f"{key}: empty")
            header = [
                f"# akari built-in block list `{key}` (W29), generated by scripts/update-block-lists.py",
                f"# source: {REPO} @ {commit} ({date}), files: {', '.join(files)}",
                "# licence: MIT (see LICENSE.v2fly in this directory)",
            ]
            rendered[key] = "\n".join(header + items) + "\n"
        with open(os.path.join(tmp, "LICENSE"), encoding="utf-8") as f:
            licence = f.read()
    os.makedirs(OUT, exist_ok=True)
    for key, text in rendered.items():
        with open(os.path.join(OUT, f"{key}.txt"), "w", encoding="utf-8") as f:
            f.write(text)
    with open(os.path.join(OUT, "LICENSE.v2fly"), "w", encoding="utf-8") as f:
        f.write(licence)
    with open(os.path.join(OUT, "VERSION"), "w", encoding="utf-8") as f:
        f.write(f"{commit}\n")
    print(f"block lists updated to {commit} ({date})")


if __name__ == "__main__":
    main()
