#!/bin/sh
# Akari agent installer for node '@@NODE_NAME@@'.
# Generated by the panel for one node; the link (and the enrollment token
# inside this script) expires @@EXPIRES@@ and dies once the agent enrolls.
#
#   install / reinstall:  curl -fsSL <link> | sh   (as root; or | sudo sh)
#   without BBR + fq:     curl -fsSL <link> | sh -s -- --no-bbr
#                         (or AKARI_BBR=0 in the environment of sh)
#   uninstall:            curl -fsSL <link> | sh -s -- --uninstall
#                         (or, on an installed node, as root: akari-agent-uninstall)
#
# What it does: downloads the agent for this machine's architecture and
# checks its SHA-256, writes /etc/akari-agent/bootstrap.toml (0600: panel
# address, server name, panel CA, one-time enrollment token; no private
# key), installs the services (systemd: the agent unit and its privileged
# updater akari-agent-update.path/.service, which applies signed
# self-updates; OpenRC (Alpine, W32): /etc/init.d/akari-agent and
# akari-agent-update, with a system user akari-agent) and starts them,
# turns on TCP BBR with the fq qdisc where the kernel supports it and the
# machine lets us (W32: /etc/sysctl.d/90-akari-bbr.conf; containers with a
# read-only /proc/sys are skipped with a message), then waits until the
# agent has enrolled and connected.
# The service files are the ones the verified agent release carries
# (`akari-agent -print-unit NAME`); releases older than that get the
# systemd copies embedded in this script (OpenRC needs a release that
# carries its scripts). Self-updates install the files of each new release
# along with its binary (W23).
# Running it again is safe: it is also how nodes installed before the
# updater units existed, or whose units predate unit refresh, get the
# current ones (重装命令).
# The whole script is one compound command: sh reads it completely before
# running anything, so a download cut short runs nothing.
{
set -eu
umask 077

ORIGIN='@@ORIGIN@@'
PREFIX='@@PREFIX@@'
# The download base carries the token: it is never printed, and URLs reach
# curl/wget on stdin (not on their command lines).
BASE="$ORIGIN/$PREFIX/install/@@TOKEN@@"
PIN='@@PIN@@'
NEEDS_CERT='@@NEEDS_CERT@@'
# Node TLS domain: the agent obtains and renews its certificate itself.
TLS_DOMAIN='@@TLS_DOMAIN@@'
FALLBACK_URL='@@FALLBACK_URL@@'
SHA_amd64='@@SHA_AMD64@@'
SHA_arm64='@@SHA_ARM64@@'
VER_amd64='@@VER_AMD64@@'
VER_arm64='@@VER_ARM64@@'

@@UNINSTALL_FN@@
die() {
	printf 'akari-install: ERROR: %s\n' "$*" >&2
	exit 1
}

[ "$(id -u)" -eq 0 ] || die "run as root (… | sudo sh)"

BBR=${AKARI_BBR:-1}
for arg in "$@"; do
	case "$arg" in
	--uninstall)
		uninstall
		exit 0
		;;
	--no-bbr) BBR=0 ;;
	*) die "unknown option: $arg (--no-bbr, --uninstall)" ;;
	esac
done

# --- preflight ---------------------------------------------------------------
# The init system: systemd, or OpenRC (Alpine; W32).
if [ -d /run/systemd/system ]; then
	SVC_MGR=systemd
	sdver=$(systemctl --version 2>/dev/null | sed -n '1s/^systemd \([0-9][0-9]*\).*/\1/p')
	[ -n "$sdver" ] && [ "$sdver" -ge 250 ] || die "systemd >= 250 is required (found: ${sdver:-unknown})"
elif [ -x /sbin/openrc-run ] && command -v rc-service >/dev/null 2>&1; then
	SVC_MGR=openrc
	[ -x /sbin/supervise-daemon ] || die "OpenRC without supervise-daemon (OpenRC >= 0.45 is required)"
	rcver=$(openrc --version 2>/dev/null | sed -n '1s/.* \([0-9][0-9]*\.[0-9][0-9]*\).*/\1/p')
	rcmaj=${rcver%%.*}
	rcmin=${rcver#*.}
	{ [ "${rcmaj:-0}" -gt 0 ] || [ "${rcmin:-0}" -ge 45 ]; } 2>/dev/null ||
		die "OpenRC >= 0.45 is required (capabilities, no_new_privs; found: ${rcver:-unknown})"
	[ -d /run/openrc ] || die "OpenRC is installed but not running on this machine"
else
	die "systemd (>= 250) or OpenRC (Alpine) is required; neither is running on this machine"
fi
command -v sha256sum >/dev/null 2>&1 || die "sha256sum is required (coreutils or busybox)"

case "$(uname -m)" in
x86_64 | amd64) ARCH=amd64 ;;
aarch64 | arm64) ARCH=arm64 ;;
*) die "unsupported architecture $(uname -m) (amd64 and arm64 only)" ;;
esac

if command -v curl >/dev/null 2>&1; then
	HAVE_CURL=1
elif command -v wget >/dev/null 2>&1; then
	HAVE_CURL=0
	[ -z "$PIN" ] || die "curl is required (the panel's certificate is pinned)"
else
	die "curl or wget is required"
fi

# fetch_panel URL OUT: from the panel (pinned when PIN is set).
fetch_panel() {
	if [ "$HAVE_CURL" = 1 ]; then
		if [ -n "$PIN" ]; then
			# --pinnedpubkey is checked before any request is sent; -k only
			# disables the CA check that a self-signed panel cannot pass.
			printf 'url = "%s"\noutput = "%s"\n' "$1" "$2" |
				curl -fsS --retry 3 --proto '=https' -k --pinnedpubkey "$PIN" -K - || return 1
		else
			printf 'url = "%s"\noutput = "%s"\n' "$1" "$2" | curl -fsS --retry 3 -K - || return 1
		fi
	else
		printf '%s\n' "$1" | wget -q -O "$2" -i - || return 1
	fi
}

# fetch_public URL OUT: public HTTPS (fallback release download).
fetch_public() {
	if [ "$HAVE_CURL" = 1 ]; then
		printf 'url = "%s"\noutput = "%s"\n' "$1" "$2" |
			curl -fsSL --retry 3 --proto '=https' -K - || return 1
	else
		printf '%s\n' "$1" | wget -q -O "$2" -i - || return 1
	fi
}

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT INT TERM

# --- agent binary --------------------------------------------------------------
case "$ARCH" in
amd64) want=$SHA_amd64 ver=$VER_amd64 ;;
*) want=$SHA_arm64 ver=$VER_arm64 ;;
esac
if [ -n "$want" ]; then
	say "downloading akari-agent $ver ($ARCH) from the panel"
	fetch_panel "$BASE/agent/$want" "$TMP/akari-agent" || die "download from the panel failed"
elif [ -n "$FALLBACK_URL" ]; then
	url=$(printf '%s' "$FALLBACK_URL" | sed "s/{arch}/$ARCH/g")
	sums="${url%/*}/SHA256SUMS"
	file="${url##*/}"
	say "no agent release for $ARCH on the panel; downloading $url"
	fetch_public "$url" "$TMP/akari-agent" || die "download failed: $url"
	fetch_public "$sums" "$TMP/SHA256SUMS" || die "download failed: $sums"
	want=$(awk -v f="$file" '$2 == f || $2 == "*" f { print $1; exit }' "$TMP/SHA256SUMS")
	[ -n "$want" ] || die "$file is not listed in $sums"
else
	die "no agent binary available for $ARCH: upload a release in the panel (Updates) or set install.fallback_binary_url"
fi
got=$(sha256sum "$TMP/akari-agent" | awk '{ print $1 }')
[ "$got" = "$want" ] || die "SHA-256 mismatch for the agent binary (expected $want, got $got)"
chmod 0755 "$TMP/akari-agent"
"$TMP/akari-agent" -version >/dev/null 2>&1 || die "the downloaded agent does not run on this machine"
say "verified $("$TMP/akari-agent" -version 2>/dev/null)"

# --- files ---------------------------------------------------------------------
install -d -m 0700 "$CONF_DIR" "$CONF_DIR/tls"
cat >"$TMP/bootstrap.toml" <<'AKARI_BOOTSTRAP_EOF'
@@BOOTSTRAP@@
AKARI_BOOTSTRAP_EOF
install -m 0600 "$TMP/bootstrap.toml" "$CONF_DIR/bootstrap.toml"

if [ "$SVC_MGR" = openrc ]; then
	# W32: the scripts of the release being installed; the updater installs
	# each new release's the same way. A release that predates them cannot
	# run under OpenRC.
	for u in akari-agent akari-agent-update; do
		if ! "$TMP/akari-agent" -print-unit "$u" >"$TMP/rc.$u" 2>/dev/null || [ ! -s "$TMP/rc.$u" ]; then
			die "this agent release ($ver) has no OpenRC support: publish a newer release in the panel (Updates)"
		fi
	done
	if ! grep -q '^akari-agent:' /etc/group; then
		addgroup -S akari-agent >/dev/null || die "cannot create the group akari-agent"
	fi
	if ! grep -q '^akari-agent:' /etc/passwd; then
		adduser -S -D -H -h "$RC_STATE" -s /sbin/nologin -G akari-agent -g akari-agent akari-agent >/dev/null ||
			die "cannot create the user akari-agent"
	fi
	install -m 0755 "$TMP/rc.akari-agent" "$RC_AGENT"
	install -m 0755 "$TMP/rc.akari-agent-update" "$RC_UPDATE"
fi

# The units: those of the release being installed (the verified binary
# prints them; the updater installs each new release's units the same way),
# else this panel's copies (releases that predate -print-unit).
if [ "$SVC_MGR" = systemd ]; then
units_from_binary=1
for u in akari-agent.service akari-agent-update.service akari-agent-update.path; do
	if ! "$TMP/akari-agent" -print-unit "$u" >"$TMP/$u" 2>/dev/null || [ ! -s "$TMP/$u" ]; then
		units_from_binary=0
		break
	fi
done
if [ "$units_from_binary" = 0 ]; then
	say "this agent release does not carry its systemd units; using the installer's copies"
	cat >"$TMP/akari-agent.service" <<'AKARI_UNIT_EOF'
@@UNIT@@
AKARI_UNIT_EOF
	# The privileged updater: the agent's state directory is noexec, so
	# signed self-updates are installed by this root unit (it only ever runs
	# the installed binary).
	cat >"$TMP/akari-agent-update.service" <<'AKARI_UPDATE_SERVICE_EOF'
@@UNIT_UPDATE_SERVICE@@
AKARI_UPDATE_SERVICE_EOF
	cat >"$TMP/akari-agent-update.path" <<'AKARI_UPDATE_PATH_EOF'
@@UNIT_UPDATE_PATH@@
AKARI_UPDATE_PATH_EOF
fi
install -m 0644 "$TMP/akari-agent.service" "$UNIT"
install -m 0644 "$TMP/akari-agent-update.service" "$UPDATE_SERVICE"
install -m 0644 "$TMP/akari-agent-update.path" "$UPDATE_PATH"
install -d -m 0755 "$DROPIN_DIR"
cat >"$TMP/10-install.conf" <<'AKARI_DROPIN_EOF'
# Written by the Akari installer: TLS inbounds read the node's certificate
# from /etc/akari-agent/tls (fullchain.pem, privkey.pem) as credentials
# ($CREDENTIALS_DIRECTORY/tls_<file>). Restart the agent after renewing it.
[Service]
LoadCredential=tls:/etc/akari-agent/tls
AKARI_DROPIN_EOF
install -m 0644 "$TMP/10-install.conf" "$DROPIN_DIR/10-install.conf"
fi

install -d -m 0755 "$(dirname "$UNINSTALLER")"
cat >"$TMP/uninstall" <<'AKARI_UNINSTALL_EOF'
#!/bin/sh
# Remove the Akari agent (written by the installer).
set -eu
@@UNINSTALL_FN@@
[ "$(id -u)" -eq 0 ] || { say "run as root"; exit 1; }
uninstall
AKARI_UNINSTALL_EOF
install -m 0755 "$TMP/uninstall" "$UNINSTALLER"

# The binary last: a reinstall over a running agent swaps it atomically.
# (A hand-installed binary wins over the updater's records: a stale
# probation is dropped because the installed version differs.)
install -m 0755 "$TMP/akari-agent" "$BIN.new"
mv -f "$BIN.new" "$BIN"
rm -f "$BIN.prev"

# --- TCP BBR + fq (W32) ------------------------------------------------------
# BBR congestion control with the fq qdisc: better throughput over lossy,
# long-distance paths. Only where the kernel has it and this machine lets
# us set it (OpenVZ/LXC and other containers often have a read-only
# /proc/sys: skipped); persisted in our own sysctl drop-in (+ module load
# file) that the uninstaller removes, putting the previous settings back.
# --no-bbr (AKARI_BBR=0) skips it, and removes what an earlier install
# added. The agent itself never changes kernel settings.
bbr_enable() {
	ccf=/proc/sys/net/ipv4/tcp_congestion_control
	qdf=/proc/sys/net/core/default_qdisc
	if [ ! -r "$ccf" ] || [ ! -r "$qdf" ]; then
		say "BBR + fq: skipped (no net.core.default_qdisc / tcp_congestion_control here: a container with its own network namespace?)"
		return 0
	fi
	cc=$(cat "$ccf")
	qd=$(cat "$qdf")
	if [ -f "$BBR_CONF" ]; then
		modprobe tcp_bbr >/dev/null 2>&1 || true
		if [ "$cc" = bbr ] && [ "$qd" = fq ]; then
			say "BBR + fq: enabled ($BBR_CONF)"
		elif printf fq >"$qdf" 2>/dev/null && printf bbr >"$ccf" 2>/dev/null; then
			say "BBR + fq: enabled again ($BBR_CONF)"
		else
			say "WARNING: BBR + fq could not be applied now ($BBR_CONF stays; applies at boot)"
		fi
		return 0
	fi
	if [ "$cc" = bbr ] && [ "$qd" = fq ]; then
		say "BBR + fq: already enabled on this machine (left as it is)"
		return 0
	fi
	loaded=0
	if ! grep -qw bbr /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null; then
		if modprobe tcp_bbr >/dev/null 2>&1 && grep -qw bbr /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null; then
			loaded=1
		else
			say "BBR + fq: skipped (kernel $(uname -r) has no tcp_bbr, or modules cannot be loaded here)"
			return 0
		fi
	fi
	if ! printf fq >"$qdf" 2>/dev/null; then
		say "BBR + fq: skipped (kernel settings are read-only here: a container?)"
		return 0
	fi
	if ! printf bbr >"$ccf" 2>/dev/null; then
		printf '%s' "$qd" >"$qdf" 2>/dev/null || true
		say "BBR + fq: skipped (cannot set the congestion control here: a container?)"
		return 0
	fi
	install -d -m 0755 "$(dirname "$BBR_CONF")"
	cat >"$TMP/bbr.conf" <<EOF
# Written by the Akari agent installer (W32): TCP BBR congestion control
# with the fq qdisc. Removed by akari-agent-uninstall (which puts the
# previous settings back), or by installing again with --no-bbr.
# akari-previous: net.core.default_qdisc=$qd net.ipv4.tcp_congestion_control=$cc
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF
	install -m 0644 "$TMP/bbr.conf" "$BBR_CONF"
	if [ "$loaded" = 1 ] || grep -q '^tcp_bbr ' /proc/modules 2>/dev/null; then
		install -d -m 0755 "$(dirname "$BBR_MOD")"
		printf '# Written by the Akari agent installer (W32): see %s\ntcp_bbr\n' "$BBR_CONF" >"$TMP/bbr-mod.conf"
		install -m 0644 "$TMP/bbr-mod.conf" "$BBR_MOD"
	fi
	say "BBR + fq: enabled (was $cc + $qd; $BBR_CONF; fq applies to network interfaces as they come up, i.e. after a reboot)"
	if [ "$SVC_MGR" = openrc ] && ! rc-update show boot 2>/dev/null | grep -q '^ *sysctl '; then
		say "      NOTE: the OpenRC service sysctl is not in the boot runlevel, so $BBR_CONF is not applied at"
		say "      boot: rc-update add sysctl boot"
	fi
}
if [ "$BBR" = 0 ]; then
	if [ -f "$BBR_CONF" ]; then
		bbr_remove
	else
		say "BBR + fq: not changed (--no-bbr)"
	fi
else
	bbr_enable
fi

# --- firewall (automatic certificate) -----------------------------------------
# The CA validates over TCP 80 (HTTP-01). Open it in an active host firewall;
# a cloud firewall / security group is outside this machine (see the note at
# the end).
if [ -n "$TLS_DOMAIN" ]; then
	if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active'; then
		if ufw allow 80/tcp comment 'akari-agent certificate' >/dev/null 2>&1; then
			say "firewall (ufw): allowed TCP 80 for the certificate challenge"
		else
			say "WARNING: could not allow TCP 80 in ufw; do it by hand: ufw allow 80/tcp"
		fi
	elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
		if firewall-cmd -q --permanent --add-port=80/tcp && firewall-cmd -q --reload; then
			say "firewall (firewalld): allowed TCP 80 for the certificate challenge"
		else
			say "WARNING: could not allow TCP 80 in firewalld; do it by hand"
		fi
	fi
fi

# --- start ---------------------------------------------------------------------
# The agent's log since this start, its automatic restarts, whether it
# failed; how to read the log.
if [ "$SVC_MGR" = openrc ]; then
	AGENT_LOG=$RC_LOG/agent.log
	log_size() { { wc -c <"$AGENT_LOG"; } 2>/dev/null || echo 0; }
	agent_log() {
		size=$(log_size)
		if [ "$size" -ge "$LOG_OFF" ]; then
			tail -c +"$((LOG_OFF + 1))" "$AGENT_LOG" 2>/dev/null
		else
			cat "$AGENT_LOG" 2>/dev/null # rotated at the start
		fi
	}
	agent_restarts() { cat /run/openrc/options/akari-agent/start_count 2>/dev/null || echo 0; }
	agent_failed() { ! rc-service akari-agent status >/dev/null 2>&1; }
	LOG_HINT="tail -f $AGENT_LOG"
	RESTART_HINT="rc-service akari-agent restart"
	LOG_OFF=$(log_size)
	rc-update add akari-agent default >/dev/null 2>&1 || die "cannot add akari-agent to the default runlevel"
	rc-update add akari-agent-update default >/dev/null 2>&1 || die "cannot add akari-agent-update to the default runlevel"
	rc-service akari-agent-update restart >/dev/null 2>&1 || die "cannot start akari-agent-update"
	rc-service akari-agent restart >/dev/null 2>&1 || die "cannot start akari-agent (see $AGENT_LOG)"
else
	START=$(date +%s)
	agent_log() { journalctl -u akari-agent.service --since "@$START" -o cat --no-pager 2>/dev/null; }
	agent_restarts() { systemctl show -p NRestarts --value akari-agent.service 2>/dev/null || echo 0; }
	agent_failed() { systemctl is-failed --quiet akari-agent.service; }
	LOG_HINT="journalctl -u akari-agent -f"
	RESTART_HINT="systemctl restart akari-agent"
	systemctl daemon-reload
	systemctl enable akari-agent.service >/dev/null 2>&1
	systemctl enable --now akari-agent-update.path >/dev/null 2>&1 || die "cannot enable akari-agent-update.path"
	systemctl restart akari-agent.service
fi
restarts0=$(agent_restarts)
say "agent started; waiting for it to enroll and connect"

i=0
result=
while [ "$i" -lt 90 ]; do
	log=$(agent_log || true)
	case "$log" in
	*'"msg":"enrolled"'*'"msg":"channel established"'*)
		result=ok
		break
		;;
	*'enrollment refused'*)
		result=refused
		break
		;;
	*'too many enrollment attempts'*)
		result=ratelimited
		break
		;;
	esac
	# Restart=always / respawn: a crash loop never reaches "failed".
	restarts=$(agent_restarts)
	if agent_failed || [ $((${restarts:-0} - ${restarts0:-0})) -ge 3 ]; then
		result=failed
		break
	fi
	sleep 1
	i=$((i + 1))
done

case "$result" in
ok)
	say "SUCCESS: the agent enrolled and is connected; the node shows online in the panel."
	if [ -n "$TLS_DOMAIN" ]; then
		say "TLS certificate: the agent obtains one for $TLS_DOMAIN itself (Let's Encrypt) and renews it."
		say "      Needs: the DNS record of $TLS_DOMAIN pointing at this machine, and TCP 80 open to the"
		say "      internet (cloud firewall / security group too; TCP 443 also works when no inbound uses it)."
		say "      Status: the node page in the panel, or $LOG_HINT"
	elif [ "$NEEDS_CERT" = 1 ] && { [ ! -s "$CONF_DIR/tls/fullchain.pem" ] || [ ! -s "$CONF_DIR/tls/privkey.pem" ]; }; then
		say "NOTE: this node has TLS inbounds. Put the certificate in $CONF_DIR/tls/fullchain.pem and"
		say "      $CONF_DIR/tls/privkey.pem (0600), then: $RESTART_HINT"
	fi
	# Run through sudo: say so; as root (images without sudo): plain.
	if [ -n "${SUDO_USER:-}" ] && command -v sudo >/dev/null 2>&1; then
		say "uninstall later with: sudo $UNINSTALLER"
	else
		say "uninstall later with (as root): $UNINSTALLER"
	fi
	;;
refused)
	agent_log | tail -n 20 >&2 || true
	die "the panel refused the enrollment token (expired or already used): create a new install command in the panel"
	;;
ratelimited)
	die "the panel is rate limiting enrollments from this address; the agent keeps retrying ($LOG_HINT), or run this again in a few minutes"
	;;
*)
	agent_log | tail -n 30 >&2 || true
	die "the agent did not connect within 90 s (see the log above; $LOG_HINT)"
	;;
esac
}
