#!/bin/sh
# Akari agent installer for node '@@NODE_NAME@@'.
# Generated by the panel for one node; the link (and the enrollment token
# inside this script) expires @@EXPIRES@@ and dies once the agent enrolls.
#
#   install / reinstall:  curl -fsSL <link> | sudo sh
#   uninstall:            curl -fsSL <link> | sudo sh -s -- --uninstall
#                         (or, on an installed node: sudo akari-agent-uninstall)
#
# What it does: downloads the agent for this machine's architecture and
# checks its SHA-256, writes /etc/akari-agent/bootstrap.toml (0600: panel
# address, server name, panel CA, one-time enrollment token; no private
# key), installs the systemd unit and starts it, then waits until the agent
# has enrolled and connected. Running it again is safe.
set -eu
umask 077

ORIGIN='@@ORIGIN@@'
PREFIX='@@PREFIX@@'
# The download base carries the token: it is never printed, and URLs reach
# curl/wget on stdin (not on their command lines).
BASE="$ORIGIN/$PREFIX/install/@@TOKEN@@"
PIN='@@PIN@@'
NEEDS_CERT='@@NEEDS_CERT@@'
FALLBACK_URL='@@FALLBACK_URL@@'
SHA_amd64='@@SHA_AMD64@@'
SHA_arm64='@@SHA_ARM64@@'
VER_amd64='@@VER_AMD64@@'
VER_arm64='@@VER_ARM64@@'

@@UNINSTALL_FN@@
die() {
	printf 'akari-install: ERROR: %s\n' "$*" >&2
	exit 1
}

[ "$(id -u)" -eq 0 ] || die "run as root (… | sudo sh)"

case "${1:-}" in
--uninstall)
	uninstall
	exit 0
	;;
"") ;;
*) die "unknown option: $1 (only --uninstall)" ;;
esac

# --- preflight ---------------------------------------------------------------
[ -d /run/systemd/system ] || die "systemd is not running on this machine (required)"
sdver=$(systemctl --version 2>/dev/null | sed -n '1s/^systemd \([0-9][0-9]*\).*/\1/p')
[ -n "$sdver" ] && [ "$sdver" -ge 250 ] || die "systemd >= 250 is required (found: ${sdver:-unknown})"
command -v sha256sum >/dev/null 2>&1 || die "sha256sum is required (coreutils)"

case "$(uname -m)" in
x86_64 | amd64) ARCH=amd64 ;;
aarch64 | arm64) ARCH=arm64 ;;
*) die "unsupported architecture $(uname -m) (amd64 and arm64 only)" ;;
esac

if command -v curl >/dev/null 2>&1; then
	HAVE_CURL=1
elif command -v wget >/dev/null 2>&1; then
	HAVE_CURL=0
	[ -z "$PIN" ] || die "curl is required (the panel's certificate is pinned)"
else
	die "curl or wget is required"
fi

# fetch_panel URL OUT: from the panel (pinned when PIN is set).
fetch_panel() {
	if [ "$HAVE_CURL" = 1 ]; then
		if [ -n "$PIN" ]; then
			# --pinnedpubkey is checked before any request is sent; -k only
			# disables the CA check that a self-signed panel cannot pass.
			printf 'url = "%s"\noutput = "%s"\n' "$1" "$2" |
				curl -fsS --retry 3 --proto '=https' -k --pinnedpubkey "$PIN" -K - || return 1
		else
			printf 'url = "%s"\noutput = "%s"\n' "$1" "$2" | curl -fsS --retry 3 -K - || return 1
		fi
	else
		printf '%s\n' "$1" | wget -q -O "$2" -i - || return 1
	fi
}

# fetch_public URL OUT: public HTTPS (fallback release download).
fetch_public() {
	if [ "$HAVE_CURL" = 1 ]; then
		printf 'url = "%s"\noutput = "%s"\n' "$1" "$2" |
			curl -fsSL --retry 3 --proto '=https' -K - || return 1
	else
		printf '%s\n' "$1" | wget -q -O "$2" -i - || return 1
	fi
}

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT INT TERM

# --- agent binary --------------------------------------------------------------
eval "want=\$SHA_$ARCH"
eval "ver=\$VER_$ARCH"
if [ -n "$want" ]; then
	say "downloading akari-agent $ver ($ARCH) from the panel"
	fetch_panel "$BASE/agent/$ARCH" "$TMP/akari-agent" || die "download from the panel failed"
elif [ -n "$FALLBACK_URL" ]; then
	url=$(printf '%s' "$FALLBACK_URL" | sed "s/{arch}/$ARCH/g")
	sums="${url%/*}/SHA256SUMS"
	file="${url##*/}"
	say "no agent release for $ARCH on the panel; downloading $url"
	fetch_public "$url" "$TMP/akari-agent" || die "download failed: $url"
	fetch_public "$sums" "$TMP/SHA256SUMS" || die "download failed: $sums"
	want=$(awk -v f="$file" '$2 == f || $2 == "*" f { print $1; exit }' "$TMP/SHA256SUMS")
	[ -n "$want" ] || die "$file is not listed in $sums"
else
	die "no agent binary available for $ARCH: upload a release in the panel (Updates) or set install.fallback_binary_url"
fi
got=$(sha256sum "$TMP/akari-agent" | awk '{ print $1 }')
[ "$got" = "$want" ] || die "SHA-256 mismatch for the agent binary (expected $want, got $got)"
chmod 0755 "$TMP/akari-agent"
"$TMP/akari-agent" -version >/dev/null 2>&1 || die "the downloaded agent does not run on this machine"
say "verified $("$TMP/akari-agent" -version 2>/dev/null)"

# --- files ---------------------------------------------------------------------
install -d -m 0700 "$CONF_DIR" "$CONF_DIR/tls"
cat >"$TMP/bootstrap.toml" <<'AKARI_BOOTSTRAP_EOF'
@@BOOTSTRAP@@
AKARI_BOOTSTRAP_EOF
install -m 0600 "$TMP/bootstrap.toml" "$CONF_DIR/bootstrap.toml"

cat >"$TMP/akari-agent.service" <<'AKARI_UNIT_EOF'
@@UNIT@@
AKARI_UNIT_EOF
install -m 0644 "$TMP/akari-agent.service" "$UNIT"
install -d -m 0755 "$DROPIN_DIR"
cat >"$TMP/10-install.conf" <<'AKARI_DROPIN_EOF'
# Written by the Akari installer: TLS inbounds read the node's certificate
# from /etc/akari-agent/tls (fullchain.pem, privkey.pem) as credentials
# ($CREDENTIALS_DIRECTORY/tls_<file>). Restart the agent after renewing it.
[Service]
LoadCredential=tls:/etc/akari-agent/tls
AKARI_DROPIN_EOF
install -m 0644 "$TMP/10-install.conf" "$DROPIN_DIR/10-install.conf"

install -d -m 0755 "$(dirname "$UNINSTALLER")"
cat >"$TMP/uninstall" <<'AKARI_UNINSTALL_EOF'
#!/bin/sh
# Remove the Akari agent (written by the installer).
set -eu
@@UNINSTALL_FN@@
[ "$(id -u)" -eq 0 ] || { say "run as root"; exit 1; }
uninstall
AKARI_UNINSTALL_EOF
install -m 0755 "$TMP/uninstall" "$UNINSTALLER"

# The binary last: a reinstall over a running agent swaps it atomically.
install -m 0755 "$TMP/akari-agent" "$BIN.new"
mv -f "$BIN.new" "$BIN"

# --- start ---------------------------------------------------------------------
START=$(date +%s)
systemctl daemon-reload
systemctl enable akari-agent.service >/dev/null 2>&1
systemctl restart akari-agent.service
say "agent started; waiting for it to enroll and connect"

i=0
result=
while [ "$i" -lt 90 ]; do
	log=$(journalctl -u akari-agent.service --since "@$START" -o cat --no-pager 2>/dev/null || true)
	case "$log" in
	*'"msg":"channel established"'*)
		result=ok
		break
		;;
	*'enrollment refused'*)
		result=refused
		break
		;;
	esac
	if systemctl is-failed --quiet akari-agent.service; then
		result=failed
		break
	fi
	sleep 1
	i=$((i + 1))
done

case "$result" in
ok)
	say "SUCCESS: the agent enrolled and is connected; the node shows online in the panel."
	if [ "$NEEDS_CERT" = 1 ] && { [ ! -s "$CONF_DIR/tls/fullchain.pem" ] || [ ! -s "$CONF_DIR/tls/privkey.pem" ]; }; then
		say "NOTE: this node has TLS inbounds. Put the certificate in $CONF_DIR/tls/fullchain.pem and"
		say "      $CONF_DIR/tls/privkey.pem (0600), then: systemctl restart akari-agent"
	fi
	say "uninstall later with: sudo $UNINSTALLER"
	;;
refused)
	journalctl -u akari-agent.service --since "@$START" -o cat --no-pager -n 20 >&2 || true
	die "the panel refused the enrollment token (expired or already used): create a new install command in the panel"
	;;
*)
	journalctl -u akari-agent.service --since "@$START" -o cat --no-pager -n 30 >&2 || true
	die "the agent did not connect within 90 s (see the log above; journalctl -u akari-agent)"
	;;
esac
